// [worker-ants] generated by AI Agent (2026-03-14 17:36:48)
// [worker-ants] generated by AI Agent (2026-03-14 15:50:12)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
import { createServer } from "http";
import { parse } from "url";
import next from "next";
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
import { WebSocketServer, WebSocket } from "ws";
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
import { networkInterfaces } from "os";
import crypto from "crypto";
// [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
import { calculateRankings } from "./lib/multiplayer/ranking.mjs";
import { sanitizeName } from "./lib/multiplayer/sanitize.mjs";
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)
// /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)

const dev = process.env.NODE_ENV !== "production";
const hostname = "localhost";
const port = parseInt(process.env.PORT || "3000");

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

const MAX_PLAYERS = 5;
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
const MAX_SESSIONS = 1000;
const MAX_STATE_SIZE = 16 * 1024; // 16KB per state update
const HEARTBEAT_INTERVAL = 30_000; // 30 seconds
const SESSION_IDLE_TTL = 5 * 60_000; // 5 minutes idle timeout
// [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
const TOUCH_DEBOUNCE_MS = 10_000; // 10 seconds debounce for touchSession
const RATE_LIMIT_WINDOW = 1000; // 1 second
const RATE_LIMIT_MAX = 30; // max messages per second
// [worker-ants] generated by AI Agent (2026-03-16 20:15:49)
// Mirror of lib/tetris/constants — server can't import TS directly
const BOARD_ROWS = 22;
// /[worker-ants] generated by AI Agent (2026-03-16 20:15:49)
const BOARD_COLS = 10;
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Get the first non-internal IPv4 address for LAN discovery */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function getLocalIP() {
  const nets = networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === "IPv4" && !net.internal) {
        return net.address;
      }
    }
  }
  return "localhost";
}

// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
/** Cached local IP — resolved once at module load */
const cachedLocalIP = getLocalIP();
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)
// /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)

/** Generate a random hex ID (8 characters) */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
// [worker-ants] generated by AI Agent (2026-03-16 20:16:53)
function generateId() {
  return crypto.randomBytes(8).toString("hex");
}
// /[worker-ants] generated by AI Agent (2026-03-16 20:16:53)

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Generate a session password (16 characters for brute-force resistance) */
function generatePassword() {
  return crypto.randomBytes(8).toString("hex");
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

// [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
/** Validate game state fields from client */
function isValidState(state) {
  if (!state || typeof state !== "object") return false;
  if (typeof state.score !== "number" || state.score < 0) return false;
  if (typeof state.isGameOver !== "boolean") return false;
  if (typeof state.isPaused !== "boolean") return false;
  if (typeof state.level !== "number" || state.level < 0) return false;
  if (typeof state.linesCleared !== "number" || state.linesCleared < 0) return false;
  if (!Array.isArray(state.board) || state.board.length !== BOARD_ROWS) return false;
  // [worker-ants] generated by AI Agent (2026-03-16 20:16:01)
  for (const row of state.board) {
    if (!Array.isArray(row) || row.length !== BOARD_COLS) return false;
  }
  // Validate activePiece structure if present
  if (state.activePiece !== undefined && state.activePiece !== null) {
    const ap = state.activePiece;
    const validTypes = ["I", "O", "T", "S", "Z", "J", "L"];
    if (!validTypes.includes(ap.type)) return false;
    if (typeof ap.row !== "number" || typeof ap.col !== "number") return false;
    if (!Array.isArray(ap.shape) || ap.shape.length === 0) return false;
    for (const shapeRow of ap.shape) {
      if (!Array.isArray(shapeRow)) return false;
    }
  }
  return true;
}
  // /[worker-ants] generated by AI Agent (2026-03-16 20:16:01)
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

/** Send JSON message to a WebSocket */
function send(ws, message) {
  if (ws.readyState === WebSocket.OPEN) {
    ws.send(JSON.stringify(message));
  }
}
// /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Build a serializable player list from a session's players Map */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function getPlayerList(session) {
  return Array.from(session.players.values()).map((p) => ({
    id: p.id,
    name: p.name,
    isHost: p.isHost,
  }));
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Send a message to all players in a session */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function broadcastAll(session, message) {
  const data = JSON.stringify(message);
  for (const player of session.players.values()) {
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    if (player.ws.readyState === WebSocket.OPEN) {
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      player.ws.send(data);
    }
  }
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Send a message to all players except one (identified by excludeId) */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function broadcast(session, message, excludeId) {
  const data = JSON.stringify(message);
  for (const player of session.players.values()) {
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    if (player.id !== excludeId && player.ws.readyState === WebSocket.OPEN) {
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      player.ws.send(data);
    }
  }
}

// [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
const sessions = new Map();
/** Reverse lookup: password → session for O(1) search */
const sessionsByPassword = new Map();

// /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Find a session by password via reverse-lookup map (O(1)) */
function findSessionByPassword(password) {
  return sessionsByPassword.get(password) || null;
}

/** Remove a session and clean up reverse-lookup */
function deleteSession(sessionId) {
  const session = sessions.get(sessionId);
  if (session) {
    sessionsByPassword.delete(session.password);
    if (session.idleTimer) clearTimeout(session.idleTimer);
    sessions.delete(sessionId);
  }
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
// [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
/** Reset idle timer with debounce — avoids timer churn from frequent state updates */
function touchSession(session) {
  const now = Date.now();
  if (now - (session.lastTouch || 0) < TOUCH_DEBOUNCE_MS) return;
  session.lastTouch = now;
// /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
  if (session.idleTimer) clearTimeout(session.idleTimer);
  session.idleTimer = setTimeout(() => {
    // Close all remaining connections
    for (const player of session.players.values()) {
      if (player.ws.readyState === WebSocket.OPEN) {
        player.ws.close(1000, "Session expired");
      }
    }
    deleteSession(session.id);
  }, SESSION_IDLE_TTL);
}
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

/**
 // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
 * Check if the round should end and broadcast results.
 * Ends when all remaining players are game-over, or only 1 player remains mid-game.
 // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
 * Uses gameStarted as an idempotency guard — Node.js single-threaded
 * event loop ensures no race between handlers.
 */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
function checkRoundEnd(session) {
  if (!session.gameStarted) return;

  const players = Array.from(session.players.values());
  if (players.length === 0) return;

  const allDead = players.every((p) => p.state?.isGameOver === true);
  // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
  const singleSurvivor = players.length === 1;

  if (!allDead && !singleSurvivor) return;

  const entries = players.map((p) => ({
    id: p.id,
    name: p.name,
    score: p.state?.score || 0,
  }));
  const rankings = calculateRankings(entries);

  broadcastAll(session, { type: "round_end", rankings });
  session.gameStarted = false;
}
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
/** Handle create_session message */
// [worker-ants] generated by AI Agent (2026-03-16 20:16:12)
function handleCreateSession(conn, ws, msg) {
  if (conn.playerId) return; // Prevent duplicate session creation
  if (sessions.size >= MAX_SESSIONS) {
// /[worker-ants] generated by AI Agent (2026-03-16 20:16:12)
    send(ws, { type: "error", error: "Server is at capacity. Try again later." });
    return;
  }

  const sessionId = generateId();
  const password = generatePassword();
  conn.playerId = generateId();
  conn.sessionId = sessionId;
  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  const name = sanitizeName(msg.playerName, "Host");
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

  const session = {
    id: sessionId,
    password,
    hostId: conn.playerId,
    players: new Map(),
    gameStarted: false,
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    idleTimer: null,
    lastTouch: 0,
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  };

  session.players.set(conn.playerId, {
    id: conn.playerId,
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    name,
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    isHost: true,
    ws,
    state: null,
  });

  sessions.set(sessionId, session);
  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  sessionsByPassword.set(password, session);
  touchSession(session);
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

  const endpoint = `ws://${cachedLocalIP}:${port}/ws`;

  send(ws, {
    type: "session_created",
    password,
    endpoint,
    playerId: conn.playerId,
  });
}

/** Handle join_session message */
// [worker-ants] generated by AI Agent (2026-03-16 20:16:24)
function handleJoinSession(conn, ws, msg) {
  if (conn.playerId) return; // Prevent duplicate session join
  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  if (typeof msg.password !== "string") return;
// /[worker-ants] generated by AI Agent (2026-03-16 20:16:24)

  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  const session = findSessionByPassword(msg.password);

  if (!session) {
    send(ws, {
      type: "join_result",
      success: false,
      error: "Invalid password. Session not found.",
    });
    return;
  }
  if (session.gameStarted) {
    send(ws, {
      type: "join_result",
      success: false,
      error: "Game already in progress.",
    });
    return;
  }
  if (session.players.size >= MAX_PLAYERS) {
    send(ws, {
      type: "join_result",
      success: false,
      error: `Session is full (max ${MAX_PLAYERS} players).`,
    });
    return;
  }

  conn.playerId = generateId();
  conn.sessionId = session.id;
  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  const name = sanitizeName(msg.playerName, "Guest");
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

  session.players.set(conn.playerId, {
    id: conn.playerId,
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    name,
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    isHost: false,
    ws,
    state: null,
  });

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  touchSession(session);
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  const players = getPlayerList(session);

  send(ws, {
    type: "join_result",
    success: true,
    playerId: conn.playerId,
    players,
  });

  broadcast(
    session,
    {
      type: "player_joined",
      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      player: { id: conn.playerId, name, isHost: false },
      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      players,
    },
    conn.playerId
  );
}

/** Handle start_game message */
function handleStartGame(conn, ws) {
  const session = sessions.get(conn.sessionId);
  if (!session || session.hostId !== conn.playerId) {
    send(ws, { type: "error", error: "Cannot start game." });
    return;
  }
  if (session.gameStarted) return;
  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  if (session.players.size < 2) {
    send(ws, { type: "error", error: "Need at least 2 players to start." });
    return;
  }
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

  session.gameStarted = true;
  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  touchSession(session);
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  broadcastAll(session, { type: "game_started" });
}

/** Handle state_update message */
function handleStateUpdate(conn, ws, msg) {
  const session = sessions.get(conn.sessionId);
  if (!session || !conn.playerId) return;

  // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
  // Validate state structure and field types
  if (!isValidState(msg.state)) return;
  // [worker-ants] generated by AI Agent (2026-03-16 20:16:43)
  // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

  // Validate score increase is reasonable (anti-cheat)
  const existingPlayer = session.players.get(conn.playerId);
  if (existingPlayer?.state) {
    const scoreDelta = msg.state.score - existingPlayer.state.score;
    if (scoreDelta > 0) {
      const maxDelta = 10000 * (msg.state.level + 1);
      if (scoreDelta > maxDelta) return;
    }
  }

  const player = existingPlayer;
  if (player) {
    player.state = msg.state;
  }

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  touchSession(session);

  // Broadcast only the changed player's state
  broadcast(session, {
    type: "state_broadcast",
    states: { [conn.playerId]: msg.state },
  }, conn.playerId);
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  // /[worker-ants] generated by AI Agent (2026-03-16 20:16:43)

  checkRoundEnd(session);
}

/** Handle WebSocket close event */
function handleClose(conn) {
  if (!conn.sessionId || !conn.playerId) return;

  const session = sessions.get(conn.sessionId);
  if (!session) return;

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  const wasHost = session.hostId === conn.playerId;
  // [worker-ants] generated by AI Agent (2026-03-16 20:17:12)
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  // Preserve disconnected player's state for potential round-end ranking
  const disconnectedPlayer = session.players.get(conn.playerId);
  const disconnectedState = disconnectedPlayer ? {
    id: disconnectedPlayer.id,
    name: disconnectedPlayer.name,
    state: disconnectedPlayer.state
  } : null;
  session.players.delete(conn.playerId);
  // /[worker-ants] generated by AI Agent (2026-03-16 20:17:12)

  if (session.players.size === 0) {
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    deleteSession(conn.sessionId);
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    return;
  }

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  // Reassign host if host left
  if (wasHost) {
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    const newHost = session.players.values().next().value;
    if (newHost) {
      newHost.isHost = true;
      session.hostId = newHost.id;
    }
  }

  // Build player list once (avoids double getPlayerList call)
  const players = getPlayerList(session);

  if (wasHost) {
    broadcastAll(session, {
      type: "host_transferred",
      newHostId: session.hostId,
      players,
    });
  }

  broadcastAll(session, {
    type: "player_left",
    playerId: conn.playerId,
    players,
  });
// [worker-ants] generated by AI Agent (2026-03-16 20:17:28)
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)

  // Check if round should end after player leaves
  // Include disconnected player's score in rankings if round ends
  if (session.gameStarted) {
    const players = Array.from(session.players.values());
    if (players.length === 0) return;

    const allDead = players.every((p) => p.state?.isGameOver === true);
    const singleSurvivor = players.length === 1;

    if (allDead || singleSurvivor) {
      const entries = players.map((p) => ({
        id: p.id,
        name: p.name,
        score: p.state?.score || 0,
      }));
      // Include disconnected player in rankings
      if (disconnectedState?.state) {
        entries.push({
          id: disconnectedState.id,
          name: disconnectedState.name,
          score: disconnectedState.state.score || 0,
        });
      }
      const rankings = calculateRankings(entries);
      broadcastAll(session, { type: "round_end", rankings });
      session.gameStarted = false;
    }
  }
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
}
// /[worker-ants] generated by AI Agent (2026-03-16 20:17:28)
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

app.prepare().then(() => {
  const server = createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    } catch (err) {
      console.error("Error handling", req.url, err);
      res.statusCode = 500;
      res.end("internal server error");
    }
  });

  const wss = new WebSocketServer({ noServer: true });

  // Forward WebSocket upgrade events: game traffic → wss, HMR → Next.js
  const nextUpgradeHandler = app.getUpgradeHandler();
  server.on("upgrade", (req, socket, head) => {
    const { pathname } = parse(req.url, true);
    if (pathname === "/ws") {
      wss.handleUpgrade(req, socket, head, (ws) => {
        wss.emit("connection", ws, req);
      });
    } else {
      nextUpgradeHandler(req, socket, head);
    }
  });

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  // Heartbeat: detect broken connections via ping/pong
  const heartbeatInterval = setInterval(() => {
    for (const ws of wss.clients) {
      if (ws.isAlive === false) {
        ws.terminate();
        continue;
      }
      ws.isAlive = false;
      ws.ping();
    }
  }, HEARTBEAT_INTERVAL);

  wss.on("close", () => clearInterval(heartbeatInterval));

  wss.on("connection", (ws, req) => {
    // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
    // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
    // Origin validation (CSWSH defense) — reject missing or unknown origins
    // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
    const origin = req.headers.origin;
    const allowedOrigins = [
      `http://localhost:${port}`,
      `http://127.0.0.1:${port}`,
      // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
      `http://${cachedLocalIP}:${port}`,
    ];
    if (!origin || !allowedOrigins.includes(origin)) {
      // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
      ws.close(1008, "Invalid origin");
      return;
    }
    // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

    // [worker-ants] generated by AI Agent (2026-03-15 00:53:13)
    ws.isAlive = true;

  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
    const conn = { playerId: null, sessionId: null, msgCount: 0, msgWindowStart: Date.now() };
    // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

    // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
    ws.on("pong", () => {
      ws.isAlive = true;
      // Keep session alive on pong
      if (conn.sessionId) {
        const session = sessions.get(conn.sessionId);
        if (session) touchSession(session);
      }
    });
    // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)
    // /[worker-ants] generated by AI Agent (2026-03-15 00:53:13)

    ws.on("message", (raw) => {
      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      // Message size limit (raw bytes)
      if (raw.length > MAX_STATE_SIZE) return;

      // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
      // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
      // Rate limiting
      const now = Date.now();
      if (now - conn.msgWindowStart > RATE_LIMIT_WINDOW) {
        conn.msgCount = 0;
        conn.msgWindowStart = now;
      }
      conn.msgCount++;
      if (conn.msgCount > RATE_LIMIT_MAX) return;
      // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

      // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      let msg;
      try {
        msg = JSON.parse(raw.toString());
      } catch {
        return;
      }

      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      if (!msg || typeof msg.type !== "string") return;

      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      switch (msg.type) {
        // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
        case "create_session":
          handleCreateSession(conn, ws, msg);
          break;
        case "join_session":
          handleJoinSession(conn, ws, msg);
          break;
        case "start_game":
          handleStartGame(conn, ws);
          break;
        case "state_update":
          handleStateUpdate(conn, ws, msg);
        // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
          break;
      }
    });

    // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
    ws.on("close", () => handleClose(conn));
    // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
  });

  server.listen(port, "0.0.0.0", () => {
    console.log(`> Ready on http://localhost:${port}`);
    // [worker-ants] generated by AI Agent (2026-03-15 00:52:43)
    console.log(`> WebSocket on ws://${cachedLocalIP}:${port}/ws`);
    // /[worker-ants] generated by AI Agent (2026-03-15 00:52:43)
  });
});
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:50:12)
// /[worker-ants] generated by AI Agent (2026-03-14 17:36:48)
