// [worker-ants] generated by AI Agent (2026-03-14 15:50:12)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
import { createServer } from "http";
import { parse } from "url";
import next from "next";
import { WebSocketServer } from "ws";
import { networkInterfaces } from "os";
import crypto from "crypto";

const dev = process.env.NODE_ENV !== "production";
const hostname = "localhost";
const port = parseInt(process.env.PORT || "3000");

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

const MAX_PLAYERS = 5;
const sessions = new Map();

function generateId() {
  return crypto.randomBytes(4).toString("hex");
}

function generatePassword() {
  return crypto.randomBytes(4).toString("hex");
}

function getLocalIP() {
  const nets = networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === "IPv4" && !net.internal) {
        return net.address;
      }
    }
  }
  return "localhost";
}

function getPlayerList(session) {
  return Array.from(session.players.values()).map((p) => ({
    id: p.id,
    name: p.name,
    isHost: p.isHost,
  }));
}

function broadcastAll(session, message) {
  const data = JSON.stringify(message);
  for (const player of session.players.values()) {
    if (player.ws.readyState === 1) {
      player.ws.send(data);
    }
  }
}

function broadcast(session, message, excludeId) {
  const data = JSON.stringify(message);
  for (const player of session.players.values()) {
    if (player.id !== excludeId && player.ws.readyState === 1) {
      player.ws.send(data);
    }
  }
}

function findSessionByPassword(password) {
  for (const session of sessions.values()) {
    if (session.password === password) {
      return session;
    }
  }
  return null;
}

function checkRoundEnd(session) {
  if (!session.gameStarted) return;

  const players = Array.from(session.players.values());
  if (players.length === 0) return;

  const allDead = players.every((p) => p.state?.isGameOver === true);
  if (!allDead) return;

  const rankings = players
    .map((p) => ({
      playerId: p.id,
      name: p.name,
      score: p.state?.score || 0,
    }))
    .sort((a, b) => b.score - a.score)
    .map((entry, index) => ({ ...entry, rank: index + 1 }));

  broadcastAll(session, { type: "round_end", rankings });
  session.gameStarted = false;
}

app.prepare().then(() => {
  const server = createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    } catch (err) {
      console.error("Error handling", req.url, err);
      res.statusCode = 500;
      res.end("internal server error");
    }
  });

  const wss = new WebSocketServer({ server, path: "/ws" });

  wss.on("connection", (ws) => {
    let playerId = null;
    let currentSessionId = null;

    ws.on("message", (raw) => {
      let msg;
      try {
        msg = JSON.parse(raw.toString());
      } catch {
        return;
      }

      switch (msg.type) {
        case "create_session": {
          const sessionId = generateId();
          const password = generatePassword();
          playerId = generateId();
          currentSessionId = sessionId;

          const session = {
            id: sessionId,
            password,
            hostId: playerId,
            players: new Map(),
            gameStarted: false,
          };

          session.players.set(playerId, {
            id: playerId,
            name: msg.playerName || "Host",
            isHost: true,
            ws,
            state: null,
          });

          sessions.set(sessionId, session);

          const ip = getLocalIP();
          const endpoint = `ws://${ip}:${port}/ws`;

          ws.send(
            JSON.stringify({
              type: "session_created",
              password,
              endpoint,
              playerId,
            })
          );
          break;
        }

        case "join_session": {
          const session = findSessionByPassword(msg.password);

          if (!session) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: "Invalid password. Session not found.",
              })
            );
            break;
          }
          if (session.gameStarted) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: "Game already in progress.",
              })
            );
            break;
          }
          if (session.players.size >= MAX_PLAYERS) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: `Session is full (max ${MAX_PLAYERS} players).`,
              })
            );
            break;
          }

          playerId = generateId();
          currentSessionId = session.id;

          session.players.set(playerId, {
            id: playerId,
            name: msg.playerName || "Guest",
            isHost: false,
            ws,
            state: null,
          });

          const players = getPlayerList(session);

          ws.send(
            JSON.stringify({
              type: "join_result",
              success: true,
              playerId,
              players,
            })
          );

          broadcast(
            session,
            {
              type: "player_joined",
              player: {
                id: playerId,
                name: msg.playerName || "Guest",
                isHost: false,
              },
              players,
            },
            playerId
          );
          break;
        }

        case "start_game": {
          const session = sessions.get(currentSessionId);
          if (!session || session.hostId !== playerId) break;
          if (session.gameStarted) break;

          session.gameStarted = true;
          broadcastAll(session, { type: "game_started" });
          break;
        }

        case "state_update": {
          const session = sessions.get(currentSessionId);
          if (!session || !playerId) break;

          const player = session.players.get(playerId);
          if (player) {
            player.state = msg.state;
          }

          // Broadcast all player states
          const states = {};
          for (const [id, p] of session.players) {
            if (p.state) {
              states[id] = p.state;
            }
          }
          broadcastAll(session, { type: "state_broadcast", states });

          checkRoundEnd(session);
          break;
        }
      }
    });

    ws.on("close", () => {
      if (!currentSessionId || !playerId) return;

      const session = sessions.get(currentSessionId);
      if (!session) return;

      session.players.delete(playerId);

      if (session.players.size === 0) {
        sessions.delete(currentSessionId);
        return;
      }

      // Reassign host if host left
      if (session.hostId === playerId) {
        const newHost = session.players.values().next().value;
        if (newHost) {
          newHost.isHost = true;
          session.hostId = newHost.id;
        }
      }

      const players = getPlayerList(session);
      broadcastAll(session, {
        type: "player_left",
        playerId,
        players,
      });
    });
  });

  server.listen(port, "0.0.0.0", () => {
    console.log(`> Ready on http://localhost:${port}`);
    console.log(`> WebSocket on ws://${getLocalIP()}:${port}/ws`);
  });
});
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:50:12)
