// [worker-ants] generated by AI Agent (2026-03-14 15:50:12)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
import { createServer } from "http";
import { parse } from "url";
import next from "next";
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
import { WebSocketServer, WebSocket } from "ws";
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
import { networkInterfaces } from "os";
import crypto from "crypto";

const dev = process.env.NODE_ENV !== "production";
const hostname = "localhost";
const port = parseInt(process.env.PORT || "3000");

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

const MAX_PLAYERS = 5;
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
const MAX_SESSIONS = 1000;
const MAX_NAME_LENGTH = 16;
const MAX_STATE_SIZE = 16 * 1024; // 16KB per state update
const HEARTBEAT_INTERVAL = 30_000; // 30 seconds
const SESSION_IDLE_TTL = 5 * 60_000; // 5 minutes idle timeout

const sessions = new Map();
/** Reverse lookup: password → session for O(1) search */
const sessionsByPassword = new Map();

/** Generate a random hex ID (8 characters) */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function generateId() {
  return crypto.randomBytes(4).toString("hex");
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Generate a session password (16 characters for brute-force resistance) */
function generatePassword() {
  return crypto.randomBytes(8).toString("hex");
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Get the first non-internal IPv4 address for LAN discovery */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function getLocalIP() {
  const nets = networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === "IPv4" && !net.internal) {
        return net.address;
      }
    }
  }
  return "localhost";
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Build a serializable player list from a session's players Map */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function getPlayerList(session) {
  return Array.from(session.players.values()).map((p) => ({
    id: p.id,
    name: p.name,
    isHost: p.isHost,
  }));
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Send a message to all players in a session */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function broadcastAll(session, message) {
  const data = JSON.stringify(message);
  for (const player of session.players.values()) {
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    if (player.ws.readyState === WebSocket.OPEN) {
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      player.ws.send(data);
    }
  }
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Send a message to all players except one (identified by excludeId) */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function broadcast(session, message, excludeId) {
  const data = JSON.stringify(message);
  for (const player of session.players.values()) {
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    if (player.id !== excludeId && player.ws.readyState === WebSocket.OPEN) {
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      player.ws.send(data);
    }
  }
}

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Find a session by password via reverse-lookup map (O(1)) */
function findSessionByPassword(password) {
  return sessionsByPassword.get(password) || null;
}

/** Validate and sanitize player name */
function sanitizeName(name, fallback) {
  if (typeof name !== "string" || !name.trim()) return fallback;
  return name.trim().slice(0, MAX_NAME_LENGTH);
}

/** Remove a session and clean up reverse-lookup */
function deleteSession(sessionId) {
  const session = sessions.get(sessionId);
  if (session) {
    sessionsByPassword.delete(session.password);
    if (session.idleTimer) clearTimeout(session.idleTimer);
    sessions.delete(sessionId);
  }
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
/** Reset idle timer — auto-deletes session after SESSION_IDLE_TTL of inactivity */
function touchSession(session) {
  if (session.idleTimer) clearTimeout(session.idleTimer);
  session.idleTimer = setTimeout(() => {
    // Close all remaining connections
    for (const player of session.players.values()) {
      if (player.ws.readyState === WebSocket.OPEN) {
        player.ws.close(1000, "Session expired");
      }
    }
    deleteSession(session.id);
  }, SESSION_IDLE_TTL);
}

/**
 * Check if all players are dead and end the round if so.
 * Uses gameStarted as an idempotency guard — Node.js single-threaded
 * event loop ensures no race between handlers.
 */
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
function checkRoundEnd(session) {
  if (!session.gameStarted) return;

  const players = Array.from(session.players.values());
  if (players.length === 0) return;

  const allDead = players.every((p) => p.state?.isGameOver === true);
  if (!allDead) return;

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  const sorted = players
  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    .map((p) => ({
      playerId: p.id,
      name: p.name,
      score: p.state?.score || 0,
    }))
    // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    .sort((a, b) => b.score - a.score);

  let currentRank = 1;
  const rankings = sorted.map((entry, index) => {
    if (index > 0 && entry.score < sorted[index - 1].score) {
      currentRank = index + 1;
    }
    return { ...entry, rank: currentRank };
  });
    // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

  broadcastAll(session, { type: "round_end", rankings });
  session.gameStarted = false;
}

app.prepare().then(() => {
  const server = createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    } catch (err) {
      console.error("Error handling", req.url, err);
      res.statusCode = 500;
      res.end("internal server error");
    }
  });

  const wss = new WebSocketServer({ server, path: "/ws" });

  // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
  // Heartbeat: detect broken connections via ping/pong
  const heartbeatInterval = setInterval(() => {
    for (const ws of wss.clients) {
      if (ws.isAlive === false) {
        ws.terminate();
        continue;
      }
      ws.isAlive = false;
      ws.ping();
    }
  }, HEARTBEAT_INTERVAL);

  wss.on("close", () => clearInterval(heartbeatInterval));

  wss.on("connection", (ws, req) => {
    // Origin validation (CSWSH defense)
    const origin = req.headers.origin;
    const allowedOrigins = [
      `http://localhost:${port}`,
      `http://127.0.0.1:${port}`,
      `http://${getLocalIP()}:${port}`,
    ];
    if (origin && !allowedOrigins.includes(origin)) {
      ws.close(1008, "Invalid origin");
      return;
    }

    ws.isAlive = true;
    ws.on("pong", () => { ws.isAlive = true; });

  // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    let playerId = null;
    let currentSessionId = null;

    ws.on("message", (raw) => {
      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      // Message size limit (raw bytes)
      if (raw.length > MAX_STATE_SIZE) return;

      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      let msg;
      try {
        msg = JSON.parse(raw.toString());
      } catch {
        return;
      }

      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      if (!msg || typeof msg.type !== "string") return;

      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      switch (msg.type) {
        case "create_session": {
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          // Session creation limit
          if (sessions.size >= MAX_SESSIONS) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: "Server is at capacity. Try again later.",
              })
            );
            break;
          }

          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          const sessionId = generateId();
          const password = generatePassword();
          playerId = generateId();
          currentSessionId = sessionId;
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          const name = sanitizeName(msg.playerName, "Host");
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

          const session = {
            id: sessionId,
            password,
            hostId: playerId,
            players: new Map(),
            gameStarted: false,
            // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
            idleTimer: null,
            // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          };

          session.players.set(playerId, {
            id: playerId,
            // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
            name,
            // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
            isHost: true,
            ws,
            state: null,
          });

          sessions.set(sessionId, session);
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          sessionsByPassword.set(password, session);
          touchSession(session);
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

          const ip = getLocalIP();
          const endpoint = `ws://${ip}:${port}/ws`;

          ws.send(
            JSON.stringify({
              type: "session_created",
              password,
              endpoint,
              playerId,
            })
          );
          break;
        }

        case "join_session": {
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          if (typeof msg.password !== "string") break;

          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          const session = findSessionByPassword(msg.password);

          if (!session) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: "Invalid password. Session not found.",
              })
            );
            break;
          }
          if (session.gameStarted) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: "Game already in progress.",
              })
            );
            break;
          }
          if (session.players.size >= MAX_PLAYERS) {
            ws.send(
              JSON.stringify({
                type: "join_result",
                success: false,
                error: `Session is full (max ${MAX_PLAYERS} players).`,
              })
            );
            break;
          }

          playerId = generateId();
          currentSessionId = session.id;
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          const name = sanitizeName(msg.playerName, "Guest");
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

          session.players.set(playerId, {
            id: playerId,
            // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
            name,
            // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
            isHost: false,
            ws,
            state: null,
          });

          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          touchSession(session);
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          const players = getPlayerList(session);

          ws.send(
            JSON.stringify({
              type: "join_result",
              success: true,
              playerId,
              players,
            })
          );

          broadcast(
            session,
            {
              type: "player_joined",
              // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
              player: { id: playerId, name, isHost: false },
              // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
              players,
            },
            playerId
          );
          break;
        }

        case "start_game": {
          const session = sessions.get(currentSessionId);
          if (!session || session.hostId !== playerId) break;
          if (session.gameStarted) break;
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          if (session.players.size < 2) break;
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

          session.gameStarted = true;
          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          touchSession(session);
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          broadcastAll(session, { type: "game_started" });
          break;
        }

        case "state_update": {
          const session = sessions.get(currentSessionId);
          if (!session || !playerId) break;

          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          // Validate state structure
          if (!msg.state || typeof msg.state !== "object") break;

          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          const player = session.players.get(playerId);
          if (player) {
            player.state = msg.state;
          }

          // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
          touchSession(session);

          // Broadcast only the changed player's state
          broadcastAll(session, {
            type: "state_broadcast",
            states: { [playerId]: msg.state },
          });
          // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)

          checkRoundEnd(session);
          break;
        }
      }
    });

    ws.on("close", () => {
      if (!currentSessionId || !playerId) return;

      const session = sessions.get(currentSessionId);
      if (!session) return;

      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      const wasHost = session.hostId === playerId;
      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      session.players.delete(playerId);

      if (session.players.size === 0) {
        // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
        deleteSession(currentSessionId);
        // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
        return;
      }

      // [worker-ants] generated by AI Agent (2026-03-14 16:37:36)
      // Reassign host if host left and notify clients
      if (wasHost) {
      // /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
        const newHost = session.players.values().next().value;
        if (newHost) {
          newHost.isHost = true;
          session.hostId = newHost.id;
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)

          const players = getPlayerList(session);
          broadcastAll(session, {
            type: "host_transferred",
            newHostId: newHost.id,
            players,
          });
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
        }
      }

      const players = getPlayerList(session);
      broadcastAll(session, {
        type: "player_left",
        playerId,
        players,
      });
// [worker-ants] generated by AI Agent (2026-03-14 16:37:36)

      // Check if round should end after player leaves
      checkRoundEnd(session);
// /[worker-ants] generated by AI Agent (2026-03-14 16:37:36)
    });
  });

  server.listen(port, "0.0.0.0", () => {
    console.log(`> Ready on http://localhost:${port}`);
    console.log(`> WebSocket on ws://${getLocalIP()}:${port}/ws`);
  });
});
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:50:12)
