// [worker-ants] generated by AI Agent (2026-03-14 14:57:19)
import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./"),
    },
  },
  test: {
    include: ["**/__tests__/**/*.test.ts"],
  },
});

// /[worker-ants] generated by AI Agent (2026-03-14 14:57:19)
