// [worker-ants] generated by AI Agent (2026-03-14 11:42:56)
"use client";

const CONTROLS = [
  { keys: "\u2190 / A", action: "Move Left" },
  { keys: "\u2192 / D", action: "Move Right" },
  { keys: "\u2193 / S", action: "Soft Drop" },
  { keys: "\u2191 / W", action: "Rotate CW" },
  { keys: "Z", action: "Rotate CCW" },
// [worker-ants] generated by AI Agent (2026-03-14 15:01:37)
// [worker-ants] generated by AI Agent (2026-03-14 12:34:08)
  { keys: "Space", action: "Hard Drop" },
  { keys: "Space / Enter", action: "Start Game" },
  { keys: "P", action: "Pause / Resume" },
  { keys: "R", action: "Restart" },
// /[worker-ants] generated by AI Agent (2026-03-14 12:34:08)
// /[worker-ants] generated by AI Agent (2026-03-14 15:01:37)
];

export default function ControlsInfo() {
  return (
    <div className="bg-gray-800 border border-gray-600 rounded p-3">
      <div className="text-gray-400 text-xs uppercase tracking-wider mb-2">Controls</div>
      <div className="flex flex-col gap-1">
        {CONTROLS.map(({ keys, action }) => (
          <div key={action} className="flex justify-between text-sm gap-3">
            <span className="text-gray-300 font-mono text-xs">{keys}</span>
            <span className="text-gray-500 text-xs">{action}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:42:56)
