// [worker-ants] generated by AI Agent (2026-03-14 11:42:41)
"use client";

import { useRef, useEffect } from "react";
import {
  CELL_SIZE,
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  BOARD_COLS,
  VISIBLE_ROWS,
} from "@/lib/tetris/constants";
import { GameState } from "@/lib/tetris/types";
import { PIECE_COLORS } from "@/lib/tetris/tetrominoes";
import { getGhostRow } from "@/lib/tetris/gameEngine";

interface GameBoardProps {
  gameState: GameState;
}

export default function GameBoard({ gameState }: GameBoardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;
    canvas.width = CANVAS_WIDTH * dpr;
    canvas.height = CANVAS_HEIGHT * dpr;
    canvas.style.width = `${CANVAS_WIDTH}px`;
    canvas.style.height = `${CANVAS_HEIGHT}px`;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.scale(dpr, dpr);

    // Background
    ctx.fillStyle = "#1a1a2e";
    ctx.fillRect(0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);

    // Grid lines
    ctx.strokeStyle = "#2a2a4a";
    ctx.lineWidth = 0.5;
    for (let r = 0; r <= VISIBLE_ROWS; r++) {
      ctx.beginPath();
      ctx.moveTo(0, r * CELL_SIZE);
      ctx.lineTo(CANVAS_WIDTH, r * CELL_SIZE);
      ctx.stroke();
    }
    for (let c = 0; c <= BOARD_COLS; c++) {
      ctx.beginPath();
      ctx.moveTo(c * CELL_SIZE, 0);
      ctx.lineTo(c * CELL_SIZE, CANVAS_HEIGHT);
      ctx.stroke();
    }

    // Locked cells (offset by 2 hidden rows)
    const hiddenRows = 2;
    for (let r = hiddenRows; r < hiddenRows + VISIBLE_ROWS; r++) {
      for (let c = 0; c < BOARD_COLS; c++) {
        const cell = gameState.board[r][c];
        if (cell.filled) {
          drawCell(ctx, c, r - hiddenRows, cell.color);
        }
      }
    }

    const { activePiece } = gameState;
    const color = PIECE_COLORS[activePiece.type];

    // Ghost piece
    if (!gameState.isGameOver) {
      const ghostRow = getGhostRow(gameState);
      for (let r = 0; r < activePiece.shape.length; r++) {
        for (let c = 0; c < activePiece.shape[r].length; c++) {
          if (!activePiece.shape[r][c]) continue;
          const drawR = ghostRow + r - hiddenRows;
          const drawC = activePiece.col + c;
          if (drawR >= 0 && drawR < VISIBLE_ROWS) {
            ctx.fillStyle = color + "33";
            ctx.fillRect(
              drawC * CELL_SIZE + 1,
              drawR * CELL_SIZE + 1,
              CELL_SIZE - 2,
              CELL_SIZE - 2
            );
            ctx.strokeStyle = color + "66";
            ctx.lineWidth = 1;
            ctx.strokeRect(
              drawC * CELL_SIZE + 1,
              drawR * CELL_SIZE + 1,
              CELL_SIZE - 2,
              CELL_SIZE - 2
            );
          }
        }
      }
    }

    // Active piece
    if (!gameState.isGameOver) {
      for (let r = 0; r < activePiece.shape.length; r++) {
        for (let c = 0; c < activePiece.shape[r].length; c++) {
          if (!activePiece.shape[r][c]) continue;
          const drawR = activePiece.row + r - hiddenRows;
          const drawC = activePiece.col + c;
          if (drawR >= 0 && drawR < VISIBLE_ROWS) {
            drawCell(ctx, drawC, drawR, color);
          }
        }
      }
    }
  }, [gameState]);

  return (
    <canvas
      ref={canvasRef}
      className="border-2 border-gray-600 rounded"
      style={{ width: CANVAS_WIDTH, height: CANVAS_HEIGHT }}
    />
  );
}

function drawCell(
  ctx: CanvasRenderingContext2D,
  col: number,
  row: number,
  color: string
) {
  const x = col * CELL_SIZE;
  const y = row * CELL_SIZE;

  // Main fill
  ctx.fillStyle = color;
  ctx.fillRect(x + 1, y + 1, CELL_SIZE - 2, CELL_SIZE - 2);

  // Highlight (top-left)
  ctx.fillStyle = "rgba(255,255,255,0.3)";
  ctx.fillRect(x + 1, y + 1, CELL_SIZE - 2, 3);
  ctx.fillRect(x + 1, y + 1, 3, CELL_SIZE - 2);

  // Shadow (bottom-right)
  ctx.fillStyle = "rgba(0,0,0,0.3)";
  ctx.fillRect(x + 1, y + CELL_SIZE - 4, CELL_SIZE - 2, 3);
  ctx.fillRect(x + CELL_SIZE - 4, y + 1, 3, CELL_SIZE - 2);
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:42:41)
