// [worker-ants] generated by AI Agent (2026-03-14 11:43:00)
"use client";

interface GameOverOverlayProps {
  score: number;
  onRestart: () => void;
}

export default function GameOverOverlay({ score, onRestart }: GameOverOverlayProps) {
  return (
    <div className="absolute inset-0 bg-black/75 flex items-center justify-center rounded">
      <div className="bg-gray-900 border border-gray-600 rounded-lg p-6 text-center">
        <h2 className="text-red-500 text-2xl font-bold mb-2">Game Over</h2>
        <p className="text-gray-300 text-lg mb-1">Final Score</p>
        <p className="text-white text-3xl font-mono font-bold mb-4">
          {score.toLocaleString()}
        </p>
        <button
          onClick={onRestart}
          className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-2 px-6 rounded transition-colors cursor-pointer"
        >
          Play Again (R)
        </button>
      </div>
    </div>
  );
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:43:00)
