// [worker-ants] generated by AI Agent (2026-03-14 15:53:11)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import { useState } from "react";
import type { GameConfig } from "@/lib/multiplayer/types";
import TetrisGame from "./TetrisGame";
import MultiplayerGame from "./MultiplayerGame";
import ModeSelection from "./ModeSelection";

export default function GameApp() {
  const [config, setConfig] = useState<GameConfig | null>(null);

  if (!config) {
    return <ModeSelection onSelect={setConfig} />;
  }

  if (config.mode === "single") {
    return (
      <div className="flex flex-col items-center gap-4">
        <TetrisGame />
        <button
          onClick={() => setConfig(null)}
          className="text-gray-400 hover:text-white text-sm transition-colors cursor-pointer"
        >
          &larr; Back to Menu
        </button>
      </div>
    );
  }

  return (
    <MultiplayerGame config={config} onBack={() => setConfig(null)} />
  );
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:53:11)
