// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import { useState } from "react";
import type { GameConfig } from "@/lib/multiplayer/types";
import TetrisGame from "./TetrisGame";
import MultiplayerGame from "./MultiplayerGame";
import ModeSelection from "./ModeSelection";

// [worker-ants] generated by AI Agent (2026-03-14 16:36:18)
// [worker-ants] generated by AI Agent (2026-03-14 16:08:37)
export default function GameApp() {
// /[worker-ants] generated by AI Agent (2026-03-14 16:08:37)
// /[worker-ants] generated by AI Agent (2026-03-14 16:36:18)
  // [worker-ants] generated by AI Agent (2026-03-14 16:08:00)
  const [config, setConfig] = useState<GameConfig | null>(null);
  const handleBack = () => setConfig(null);

  if (!config) return <ModeSelection onSelect={setConfig} />;
  if (config.mode === "single") return <TetrisGame onBack={handleBack} />;
  return <MultiplayerGame config={config} onBack={handleBack} />;
  // /[worker-ants] generated by AI Agent (2026-03-14 16:08:00)
}
// [worker-ants] generated by AI Agent (2026-03-14 16:36:34)
// /[worker-ants] generated by AI Agent (2026-03-14 16:08:26)
// /[worker-ants] generated by AI Agent (2026-03-14 16:36:34)
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)
