// [worker-ants] generated by AI Agent (2026-03-14 15:50:54)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

// [worker-ants] generated by AI Agent (2026-03-15 00:54:18)
import { useState } from "react";
import type { GameConfig } from "@/lib/multiplayer/types";
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
import { isValidWsUrl } from "@/lib/multiplayer/validation";
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

interface ModeSelectionProps {
  onSelect: (config: GameConfig) => void;
}

type Step = "mode" | "host" | "guest";
// /[worker-ants] generated by AI Agent (2026-03-15 00:54:18)

export default function ModeSelection({ onSelect }: ModeSelectionProps) {
  const [step, setStep] = useState<Step>("mode");
  const [playerName, setPlayerName] = useState("");
  const [endpoint, setEndpoint] = useState("");
  const [password, setPassword] = useState("");

  if (step === "mode") {
    return (
      <div className="flex flex-col gap-4 items-center">
        <button
          onClick={() => onSelect({ mode: "single" })}
          className="w-64 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-3 px-8 rounded text-lg transition-colors cursor-pointer"
        >
          Single Player
        </button>
        <button
          onClick={() => setStep("host")}
          className="w-64 bg-emerald-600 hover:bg-emerald-500 text-white font-semibold py-3 px-8 rounded text-lg transition-colors cursor-pointer"
        >
          Multiplayer - Host
        </button>
        <button
          onClick={() => setStep("guest")}
          className="w-64 bg-amber-600 hover:bg-amber-500 text-white font-semibold py-3 px-8 rounded text-lg transition-colors cursor-pointer"
        >
          Multiplayer - Guest
        </button>
      </div>
    );
  }

  if (step === "host") {
    return (
      <div className="bg-gray-800 border border-gray-600 rounded-lg p-6 w-80">
        <h2 className="text-white text-xl font-bold mb-4">Create Game</h2>
        <div className="flex flex-col gap-4">
          <div>
            <label className="text-gray-400 text-sm block mb-1">
              Your Name
            </label>
            <input
              type="text"
              value={playerName}
              onChange={(e) => setPlayerName(e.target.value)}
              placeholder="Enter your name"
              maxLength={16}
              className="w-full bg-gray-700 text-white border border-gray-500 rounded px-3 py-2 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <button
            onClick={() => {
              if (!playerName.trim()) return;
              onSelect({
                mode: "multiplayer",
                role: "host",
                playerName: playerName.trim(),
              });
            }}
            disabled={!playerName.trim()}
            className="bg-emerald-600 hover:bg-emerald-500 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-semibold py-2 px-6 rounded transition-colors cursor-pointer"
          >
            Create Session
          </button>
          <button
            onClick={() => setStep("mode")}
            className="text-gray-400 hover:text-white text-sm transition-colors cursor-pointer"
          >
            &larr; Back
          </button>
        </div>
      </div>
    );
  }

  // Guest step
  return (
    <div className="bg-gray-800 border border-gray-600 rounded-lg p-6 w-80">
      <h2 className="text-white text-xl font-bold mb-4">Join Game</h2>
      <div className="flex flex-col gap-4">
        <div>
          <label className="text-gray-400 text-sm block mb-1">Your Name</label>
          <input
            type="text"
            value={playerName}
            onChange={(e) => setPlayerName(e.target.value)}
            placeholder="Enter your name"
            maxLength={16}
            className="w-full bg-gray-700 text-white border border-gray-500 rounded px-3 py-2 focus:outline-none focus:border-indigo-500"
          />
        </div>
        <div>
          <label className="text-gray-400 text-sm block mb-1">Endpoint</label>
          <input
            type="text"
            value={endpoint}
            onChange={(e) => setEndpoint(e.target.value)}
            placeholder="ws://192.168.0.1:3000/ws"
            // [worker-ants] generated by AI Agent (2026-03-15 00:54:35)
            className="w-full bg-gray-700 text-white border border-gray-500 rounded px-3 py-2 font-mono text-sm focus:outline-none focus:border-indigo-500"
          />
          {/* [worker-ants] generated by AI Agent (2026-03-15 00:50:00) */}
          {endpoint.trim() && !isValidWsUrl(endpoint.trim()) && (
            <p className="text-red-400 text-xs mt-1">
              Please enter a valid WebSocket URL (ws:// or wss://)
            </p>
          )}
          {/* /[worker-ants] generated by AI Agent (2026-03-15 00:50:00) */}
        </div>
        {/* [worker-ants] generated by AI Agent (2026-03-15 00:56:45) */}
        <div>
          <label className="text-gray-400 text-sm block mb-1">Password</label>
          <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter password" className="w-full bg-gray-700 text-white border border-gray-500 rounded px-3 py-2 font-mono focus:outline-none focus:border-indigo-500" />
        </div>
        {/* /[worker-ants] generated by AI Agent (2026-03-15 00:56:45) */}
        <button
          onClick={() => {
            if (!playerName.trim() || !isValidWsUrl(endpoint.trim()) || !password.trim())
              return;
            onSelect({
              mode: "multiplayer",
              role: "guest",
              playerName: playerName.trim(),
              endpoint: endpoint.trim(),
              password: password.trim(),
            });
          }}
          disabled={
            !playerName.trim() || !isValidWsUrl(endpoint.trim()) || !password.trim()
          }
          className="bg-amber-600 hover:bg-amber-500 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-semibold py-2 px-6 rounded transition-colors cursor-pointer"
        >
          Join Session
        </button>
        <button
          onClick={() => setStep("mode")}
          className="text-gray-400 hover:text-white text-sm transition-colors cursor-pointer"
        >
          &larr; Back
        </button>
      </div>
    </div>
  );
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:50:54)
