// [worker-ants] generated by AI Agent (2026-03-14 15:51:44)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import { useEffect, useCallback } from "react";
import { useMultiplayer } from "@/app/hooks/useMultiplayer";
import { toBroadcastState } from "@/lib/multiplayer/broadcast";
import { MAX_PLAYERS } from "@/lib/multiplayer/types";
import type { GameConfig } from "@/lib/multiplayer/types";
import type { GameState } from "@/lib/tetris/types";
import TetrisGame from "./TetrisGame";
import OpponentBoard from "./OpponentBoard";
import RoundResult from "./RoundResult";

interface MultiplayerGameProps {
  config: Extract<GameConfig, { mode: "multiplayer" }>;
  onBack: () => void;
}

export default function MultiplayerGame({
  config,
  onBack,
}: MultiplayerGameProps) {
  const mp = useMultiplayer({
    role: config.role,
    playerName: config.playerName,
    endpoint: config.role === "guest" ? config.endpoint : undefined,
    password: config.role === "guest" ? config.password : undefined,
  });

  // [worker-ants] generated by AI Agent (2026-03-14 16:38:43)
  // Mount-time connection — mp.connect is intentionally excluded from deps
  // because it's stable (empty useCallback deps) and we only want one connection
  useEffect(() => {
    mp.connect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  // /[worker-ants] generated by AI Agent (2026-03-14 16:38:43)

  const handleStateChange = useCallback(
    (state: GameState) => {
      mp.sendState(toBroadcastState(state));
    },
    [mp.sendState]
  );

  const handleBack = useCallback(() => {
    mp.disconnect();
    onBack();
  }, [mp.disconnect, onBack]);

  // Lobby phase
  if (mp.phase === "lobby") {
    return (
      <div className="bg-gray-800 border border-gray-600 rounded-lg p-6 w-96">
        <h2 className="text-white text-xl font-bold mb-4">
          Multiplayer Lobby
        </h2>

        {mp.error && (
          <div className="bg-red-900/50 border border-red-500 rounded p-3 mb-4 text-red-300 text-sm">
            {mp.error}
          </div>
        )}

        {!mp.isConnected && !mp.error && (
          <div className="text-gray-400 text-sm mb-4">Connecting...</div>
        )}

        {/* [worker-ants] generated by AI Agent (2026-03-15 00:54:53) */}
        {mp.sessionInfo && mp.isHost && (
          <div className="bg-gray-700 rounded p-4 mb-4">
            <div className="text-gray-400 text-xs uppercase tracking-wider mb-2">
              Connection Info
            </div>
            <div className="flex flex-col gap-2">
              <div>
                <span className="text-gray-400 text-sm">Endpoint: </span>
                <code className="text-emerald-400 text-sm font-mono select-all">
                  {mp.sessionInfo.endpoint}
                </code>
              </div>
              <div>
                <span className="text-gray-400 text-sm">Password: </span>
                <code className="text-emerald-400 text-sm font-mono select-all">
                  {mp.sessionInfo.password}
                </code>
              </div>
            </div>
            <p className="text-gray-500 text-xs mt-2">
              Share these with other players to join.
            </p>
          </div>
        )}
        {/* /[worker-ants] generated by AI Agent (2026-03-15 00:54:53) */}

        {mp.players.length > 0 && (
          <div className="mb-4">
            <div className="text-gray-400 text-xs uppercase tracking-wider mb-2">
              Players ({mp.players.length}/{MAX_PLAYERS})
            </div>
            <div className="flex flex-col gap-1">
              {mp.players.map((player) => (
                <div
                  key={player.id}
                  className="flex items-center gap-2 text-sm"
                >
                  {player.isHost && (
                    <span className="text-yellow-400">&#9733;</span>
                  )}
                  <span
                    className={
                      player.id === mp.playerId
                        ? "text-indigo-400 font-semibold"
                        : "text-gray-300"
                    }
                  >
                    {player.name}
                    {player.id === mp.playerId && " (You)"}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* [worker-ants] generated by AI Agent (2026-03-14 16:39:15) */}
        {mp.isHost && mp.isConnected && (
          <button
            onClick={mp.startGame}
            disabled={mp.players.length < 2}
            className="w-full bg-emerald-600 hover:bg-emerald-500 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-semibold py-2 px-6 rounded transition-colors cursor-pointer mb-3"
          >
            {mp.players.length < 2
              ? "Waiting for players..."
              : "Start Game"}
          </button>
        )}

        {!mp.isHost && mp.isConnected && !mp.error && (
          <div className="text-gray-400 text-sm text-center mb-3">
            Waiting for host to start the game...
          </div>
        )}
        {/* /[worker-ants] generated by AI Agent (2026-03-14 16:39:15) */}

        <button
          onClick={handleBack}
          className="w-full bg-gray-600 hover:bg-gray-500 text-white text-sm font-semibold py-2 px-6 rounded transition-colors cursor-pointer"
        >
          Back to Menu
        </button>
      </div>
    );
  }

  // Result phase
  if (mp.phase === "result" && mp.rankings) {
    return (
      <RoundResult
        rankings={mp.rankings}
        myPlayerId={mp.playerId!}
        onBackToMenu={handleBack}
      />
    );
  }

  // Playing phase
  const opponents = mp.players.filter((p) => p.id !== mp.playerId);

  return (
    <div className="flex gap-8 items-start w-full max-w-[1400px] mx-auto">
      {/* Left: My game (takes ~50% of screen) */}
      {/* [worker-ants] generated by AI Agent (2026-03-14 16:06:24) */}
      <div className="flex-1 flex justify-end">
        <TetrisGame
          isMultiplayer
          autoStart
          onStateChange={handleStateChange}
          onBack={handleBack}
        />
      </div>
      {/* /[worker-ants] generated by AI Agent (2026-03-14 16:06:24) */}

      {/* Right: Opponents (takes ~50% of screen) */}
      <div className="flex-1">
        <div className="grid grid-cols-2 gap-4">
          {opponents.map((player) => {
            const state = mp.opponentStates[player.id];
            if (!state) return null;
            return (
              <OpponentBoard
                key={player.id}
                playerName={player.name}
                state={state}
                isHost={player.isHost}
              />
            );
          })}
        </div>
        {opponents.length === 0 && (
          <div className="text-gray-500 text-sm">
            Waiting for opponents&apos; state...
          </div>
        )}
      </div>
    </div>
  );
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:51:44)
