// [worker-ants] generated by AI Agent (2026-03-14 11:42:48)
"use client";

import { useRef, useEffect } from "react";
import { PREVIEW_CANVAS_SIZE, PREVIEW_CELL_SIZE } from "@/lib/tetris/constants";
import { PieceType } from "@/lib/tetris/types";
import { getShape, PIECE_COLORS } from "@/lib/tetris/tetrominoes";

interface NextPieceProps {
  pieceType: PieceType;
}

export default function NextPiece({ pieceType }: NextPieceProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;
    canvas.width = PREVIEW_CANVAS_SIZE * dpr;
    canvas.height = PREVIEW_CANVAS_SIZE * dpr;
    canvas.style.width = `${PREVIEW_CANVAS_SIZE}px`;
    canvas.style.height = `${PREVIEW_CANVAS_SIZE}px`;

    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.scale(dpr, dpr);

    // Background
    ctx.fillStyle = "#1a1a2e";
    ctx.fillRect(0, 0, PREVIEW_CANVAS_SIZE, PREVIEW_CANVAS_SIZE);

    const shape = getShape(pieceType, 0);
    const color = PIECE_COLORS[pieceType];

    // Center the piece in the preview
    const offsetX = (PREVIEW_CANVAS_SIZE - shape[0].length * PREVIEW_CELL_SIZE) / 2;
    const offsetY = (PREVIEW_CANVAS_SIZE - shape.length * PREVIEW_CELL_SIZE) / 2;

    for (let r = 0; r < shape.length; r++) {
      for (let c = 0; c < shape[r].length; c++) {
        if (!shape[r][c]) continue;
        const x = offsetX + c * PREVIEW_CELL_SIZE;
        const y = offsetY + r * PREVIEW_CELL_SIZE;

        ctx.fillStyle = color;
        ctx.fillRect(x + 1, y + 1, PREVIEW_CELL_SIZE - 2, PREVIEW_CELL_SIZE - 2);

        ctx.fillStyle = "rgba(255,255,255,0.3)";
        ctx.fillRect(x + 1, y + 1, PREVIEW_CELL_SIZE - 2, 3);
        ctx.fillRect(x + 1, y + 1, 3, PREVIEW_CELL_SIZE - 2);

        ctx.fillStyle = "rgba(0,0,0,0.3)";
        ctx.fillRect(x + 1, y + PREVIEW_CELL_SIZE - 4, PREVIEW_CELL_SIZE - 2, 3);
        ctx.fillRect(x + PREVIEW_CELL_SIZE - 4, y + 1, 3, PREVIEW_CELL_SIZE - 2);
      }
    }
  }, [pieceType]);

  return (
    <canvas
      ref={canvasRef}
      className="border-2 border-gray-600 rounded"
      style={{ width: PREVIEW_CANVAS_SIZE, height: PREVIEW_CANVAS_SIZE }}
    />
  );
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:42:48)
