// [worker-ants] generated by AI Agent (2026-03-14 15:51:08)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import { useRef, useEffect } from "react";
// [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
import { BOARD_COLS, VISIBLE_ROWS, HIDDEN_ROWS } from "@/lib/tetris/constants";
// /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
import { PIECE_COLORS } from "@/lib/tetris/tetrominoes";
import type { BroadcastState } from "@/lib/multiplayer/types";

// [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
const MINI_CELL_SIZE = 14; // px per cell in the miniature board
// /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
const MINI_WIDTH = BOARD_COLS * MINI_CELL_SIZE;
const MINI_HEIGHT = VISIBLE_ROWS * MINI_CELL_SIZE;

interface OpponentBoardProps {
  playerName: string;
  state: BroadcastState;
  isHost: boolean;
}

export default function OpponentBoard({
  playerName,
  state,
  isHost,
}: OpponentBoardProps) {
  // [worker-ants] generated by AI Agent (2026-03-14 16:43:25)
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const dprRef = useRef(1);

  // Canvas size initialization (once on mount)
  // /[worker-ants] generated by AI Agent (2026-03-14 16:43:25)
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const dpr = window.devicePixelRatio || 1;
    // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    dprRef.current = dpr;
    // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    canvas.width = MINI_WIDTH * dpr;
    canvas.height = MINI_HEIGHT * dpr;
    canvas.style.width = `${MINI_WIDTH}px`;
    canvas.style.height = `${MINI_HEIGHT}px`;
  // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
  }, []);

  // Draw board on every state change
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
  // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)

    const ctx = canvas.getContext("2d");
    if (!ctx) return;
// [worker-ants] generated by AI Agent (2026-03-14 16:39:51)

    ctx.save();
    ctx.setTransform(dprRef.current, 0, 0, dprRef.current, 0, 0);
// /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)

    // Background
    ctx.fillStyle = "#1a1a2e";
    ctx.fillRect(0, 0, MINI_WIDTH, MINI_HEIGHT);

    // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    // Grid — batched into a single path for performance
    // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    ctx.strokeStyle = "#2a2a4a";
    ctx.lineWidth = 0.5;
    // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    ctx.beginPath();
    // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    for (let r = 0; r <= VISIBLE_ROWS; r++) {
      ctx.moveTo(0, r * MINI_CELL_SIZE);
      ctx.lineTo(MINI_WIDTH, r * MINI_CELL_SIZE);
    }
    for (let c = 0; c <= BOARD_COLS; c++) {
      ctx.moveTo(c * MINI_CELL_SIZE, 0);
      ctx.lineTo(c * MINI_CELL_SIZE, MINI_HEIGHT);
    }
    // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    ctx.stroke();

    // Board cells
    // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
    for (let r = 0; r < VISIBLE_ROWS; r++) {
      for (let c = 0; c < BOARD_COLS; c++) {
        // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
        const boardRow = r + HIDDEN_ROWS;
        // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
        const color = state.board[boardRow]?.[c];
        if (color) {
          drawMiniCell(ctx, c, r, color);
        }
      }
    }

    // Active piece
    if (state.activePiece && !state.isGameOver) {
      const { shape, row, col, type } = state.activePiece;
      const color = PIECE_COLORS[type];
      for (let r = 0; r < shape.length; r++) {
        for (let c = 0; c < shape[r].length; c++) {
          if (!shape[r][c]) continue;
          // [worker-ants] generated by AI Agent (2026-03-14 16:39:51)
          const drawR = row + r - HIDDEN_ROWS;
          // /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
          const drawC = col + c;
          if (drawR >= 0 && drawR < VISIBLE_ROWS) {
            drawMiniCell(ctx, drawC, drawR, color);
          }
        }
      }
    }

    // Game over overlay
    if (state.isGameOver) {
      ctx.fillStyle = "rgba(0, 0, 0, 0.6)";
      ctx.fillRect(0, 0, MINI_WIDTH, MINI_HEIGHT);
      ctx.fillStyle = "#ef4444";
      ctx.font = "bold 14px sans-serif";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText("GAME OVER", MINI_WIDTH / 2, MINI_HEIGHT / 2);
    }

    // Paused overlay
    if (state.isPaused && !state.isGameOver) {
      ctx.fillStyle = "rgba(0, 0, 0, 0.5)";
      ctx.fillRect(0, 0, MINI_WIDTH, MINI_HEIGHT);
      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 14px sans-serif";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText("PAUSED", MINI_WIDTH / 2, MINI_HEIGHT / 2);
    }
// [worker-ants] generated by AI Agent (2026-03-14 16:39:51)

    ctx.restore();
// /[worker-ants] generated by AI Agent (2026-03-14 16:39:51)
  }, [state]);

  return (
    <div className="flex flex-col items-center gap-1">
      <div className="text-gray-300 text-sm font-semibold truncate max-w-[140px]">
        {isHost && <span className="text-yellow-400 mr-1">&#9733;</span>}
        {playerName}
      </div>
      <canvas
        ref={canvasRef}
        className="border border-gray-600 rounded"
        style={{ width: MINI_WIDTH, height: MINI_HEIGHT }}
      />
      <div className="flex gap-3 text-xs text-gray-400">
        <span>Score: {state.score.toLocaleString()}</span>
        <span>Lv.{state.level}</span>
      </div>
    </div>
  );
}

function drawMiniCell(
  ctx: CanvasRenderingContext2D,
  col: number,
  row: number,
  color: string
) {
  const x = col * MINI_CELL_SIZE;
  const y = row * MINI_CELL_SIZE;

  ctx.fillStyle = color;
  ctx.fillRect(x + 1, y + 1, MINI_CELL_SIZE - 2, MINI_CELL_SIZE - 2);

  // Highlight
  ctx.fillStyle = "rgba(255,255,255,0.25)";
  ctx.fillRect(x + 1, y + 1, MINI_CELL_SIZE - 2, 2);
  ctx.fillRect(x + 1, y + 1, 2, MINI_CELL_SIZE - 2);

  // Shadow
  ctx.fillStyle = "rgba(0,0,0,0.25)";
  ctx.fillRect(x + 1, y + MINI_CELL_SIZE - 3, MINI_CELL_SIZE - 2, 2);
  ctx.fillRect(x + MINI_CELL_SIZE - 3, y + 1, 2, MINI_CELL_SIZE - 2);
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:51:08)
