// [worker-ants] generated by AI Agent (2026-03-14 15:51:18)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import type { RankingEntry } from "@/lib/multiplayer/types";

interface RoundResultProps {
  rankings: RankingEntry[];
  myPlayerId: string;
  onBackToMenu: () => void;
}

const RANK_LABELS = ["1st", "2nd", "3rd", "4th", "5th"];
const RANK_COLORS = [
  "text-yellow-400",
  "text-gray-300",
  "text-amber-600",
  "text-gray-400",
  "text-gray-400",
];

export default function RoundResult({
  rankings,
  myPlayerId,
  onBackToMenu,
}: RoundResultProps) {
  const myRanking = rankings.find((r) => r.playerId === myPlayerId);

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50">
      <div className="bg-gray-800 border border-gray-600 rounded-lg p-8 max-w-md w-full mx-4">
        <h2 className="text-white text-2xl font-bold text-center mb-6">
          ROUND RESULTS
        </h2>

        <div className="flex flex-col gap-2 mb-6">
          {rankings.map((entry) => {
            const isMe = entry.playerId === myPlayerId;
            return (
              <div
                key={entry.playerId}
                className={`flex items-center justify-between px-4 py-2 rounded ${
                  isMe
                    ? "bg-indigo-600/30 border border-indigo-500"
                    : "bg-gray-700/50"
                }`}
              >
                <div className="flex items-center gap-3">
                  <span
                    className={`font-bold text-lg w-10 ${RANK_COLORS[entry.rank - 1] || "text-gray-400"}`}
                  >
                    {RANK_LABELS[entry.rank - 1] || `${entry.rank}th`}
                  </span>
                  <span
                    className={`font-semibold ${isMe ? "text-white" : "text-gray-300"}`}
                  >
                    {entry.name}
                    {isMe && (
                      <span className="text-indigo-400 text-sm ml-2">
                        (You)
                      </span>
                    )}
                  </span>
                </div>
                <span className="text-white font-mono font-bold">
                  {entry.score.toLocaleString()}
                </span>
              </div>
            );
          })}
        </div>

        {myRanking && (
          <div className="bg-indigo-600/20 border border-indigo-500/50 rounded-lg p-4 mb-6 text-center">
            <div className="text-indigo-300 text-sm">Your Rank</div>
            <div className="text-white text-3xl font-bold">
              {RANK_LABELS[myRanking.rank - 1] || `${myRanking.rank}th`}
            </div>
            <div className="text-gray-400 text-sm">
              out of {rankings.length} players
            </div>
          </div>
        )}

        <button
          onClick={onBackToMenu}
          className="w-full bg-gray-600 hover:bg-gray-500 text-white font-semibold py-3 px-6 rounded transition-colors cursor-pointer"
        >
          Back to Menu
        </button>
      </div>
    </div>
  );
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:51:18)
