// [worker-ants] generated by AI Agent (2026-03-14 11:42:52)
"use client";

interface ScorePanelProps {
  score: number;
  level: number;
  linesCleared: number;
}

export default function ScorePanel({ score, level, linesCleared }: ScorePanelProps) {
  return (
    <div className="flex flex-col gap-4">
      <StatBox label="Score" value={score.toLocaleString()} />
      <StatBox label="Level" value={level.toString()} />
      <StatBox label="Lines" value={linesCleared.toString()} />
    </div>
  );
}

function StatBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-gray-800 border border-gray-600 rounded p-3 min-w-[120px]">
      <div className="text-gray-400 text-xs uppercase tracking-wider mb-1">{label}</div>
      <div className="text-white text-xl font-mono font-bold">{value}</div>
    </div>
  );
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:42:52)
