// [worker-ants] generated by AI Agent (2026-03-14 11:43:24)
"use client";

// [worker-ants] generated by AI Agent (2026-03-14 15:00:36)
import { useReducer, useEffect, useCallback } from "react";
import { initGame } from "@/lib/tetris/gameEngine";
import { gameReducer } from "@/lib/tetris/reducer";
import { getDropInterval } from "@/lib/tetris/scoring";
import GameBoard from "./GameBoard";
import NextPiece from "./NextPiece";
import ScorePanel from "./ScorePanel";
import ControlsInfo from "./ControlsInfo";
import GameOverOverlay from "./GameOverOverlay";
// /[worker-ants] generated by AI Agent (2026-03-14 15:00:36)

export default function TetrisGame() {
  const [state, dispatch] = useReducer(gameReducer, null, initGame);

  // [worker-ants] generated by AI Agent (2026-03-14 15:00:52)
  // Gravity tick
  useEffect(() => {
    if (state.isGameOver || state.isPaused || !state.isStarted) return;

    const interval = getDropInterval(state.level);
    const timer = setInterval(() => dispatch({ type: "TICK" }), interval);
    return () => clearInterval(timer);
  }, [state.level, state.isGameOver, state.isPaused, state.isStarted]);
  // /[worker-ants] generated by AI Agent (2026-03-14 15:00:52)

// [worker-ants] generated by AI Agent (2026-03-14 12:33:36)
  // Keyboard controls
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      // [worker-ants] generated by AI Agent (2026-03-14 15:01:07)
      // Allow restart anytime during game over (R key only to prevent accidental restarts)
      if (state.isGameOver) {
        if (e.key === "r" || e.key === "R") {
          e.preventDefault();
          dispatch({ type: "RESTART" });
        }
        return;
      }
      // /[worker-ants] generated by AI Agent (2026-03-14 15:01:07)

      // Before game starts, only Space and Enter can start
      if (!state.isStarted) {
        if (e.key === " " || e.key === "Enter") {
          e.preventDefault();
          dispatch({ type: "START" });
        }
        return;
      }

      switch (e.key) {
        case "ArrowLeft":
        case "a":
        case "A":
          e.preventDefault();
          dispatch({ type: "MOVE_LEFT" });
          break;
        case "ArrowRight":
        case "d":
        case "D":
          e.preventDefault();
          dispatch({ type: "MOVE_RIGHT" });
          break;
        case "ArrowDown":
        case "s":
        case "S":
          e.preventDefault();
          dispatch({ type: "SOFT_DROP" });
          break;
        case "ArrowUp":
        case "w":
        case "W":
          e.preventDefault();
          dispatch({ type: "ROTATE_CW" });
          break;
        case "z":
        case "Z":
          e.preventDefault();
          dispatch({ type: "ROTATE_CCW" });
          break;
        case " ":
          e.preventDefault();
          dispatch({ type: "HARD_DROP" });
          break;
        case "p":
        case "P":
          e.preventDefault();
          dispatch({ type: "TOGGLE_PAUSE" });
          break;
        case "r":
        case "R":
          e.preventDefault();
          dispatch({ type: "RESTART" });
          break;
      }
    },
    [state.isGameOver, state.isStarted]
  );
// /[worker-ants] generated by AI Agent (2026-03-14 12:33:36)

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [handleKeyDown]);

  return (
    // [worker-ants] generated by AI Agent (2026-03-14 12:33:58)
    <div className="flex gap-6 items-start">
      <div className="relative">
        <GameBoard gameState={state} />
        {!state.isStarted && !state.isGameOver && (
          <div className="absolute inset-0 bg-black/75 flex items-center justify-center rounded">
            <div className="text-center">
              <h2 className="text-white text-3xl font-bold mb-4">TETRIS</h2>
              <button
                onClick={() => dispatch({ type: "START" })}
                className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-3 px-8 rounded text-lg transition-colors cursor-pointer mb-3"
              >
                Start
              </button>
              {/* [worker-ants] generated by AI Agent (2026-03-14 15:01:21) */}
              <p className="text-gray-400 text-sm">Press Space or Enter to start</p>
              {/* /[worker-ants] generated by AI Agent (2026-03-14 15:01:21) */}
            </div>
          </div>
        )}
        {state.isPaused && state.isStarted && !state.isGameOver && (
          <div className="absolute inset-0 bg-black/60 flex items-center justify-center rounded">
            <div className="text-center">
              <span className="text-white text-3xl font-bold block mb-4">PAUSED</span>
              <div className="flex gap-3">
                <button
                  onClick={() => dispatch({ type: "TOGGLE_PAUSE" })}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-2 px-6 rounded transition-colors cursor-pointer"
                >
                  Resume (P)
                </button>
                <button
                  onClick={() => dispatch({ type: "RESTART" })}
                  className="bg-gray-600 hover:bg-gray-500 text-white font-semibold py-2 px-6 rounded transition-colors cursor-pointer"
                >
                  Restart (R)
                </button>
              </div>
            </div>
          </div>
        )}
        {state.isGameOver && (
          <GameOverOverlay
            score={state.score}
            onRestart={() => dispatch({ type: "RESTART" })}
          />
        )}
      </div>
      <div className="flex flex-col gap-4">
        <div className="bg-gray-800 border border-gray-600 rounded p-3">
          <div className="text-gray-400 text-xs uppercase tracking-wider mb-2">Next</div>
          <NextPiece pieceType={state.nextPiece} />
        </div>
        <ScorePanel
          score={state.score}
          level={state.level}
          linesCleared={state.linesCleared}
        />
        <ControlsInfo />
        {state.isStarted && !state.isGameOver && (
          <div className="flex gap-2">
            <button
              onClick={() => dispatch({ type: "TOGGLE_PAUSE" })}
              className="flex-1 bg-gray-700 hover:bg-gray-600 text-white text-sm font-semibold py-2 px-3 rounded transition-colors cursor-pointer"
            >
              {state.isPaused ? "Resume" : "Pause"}
            </button>
            <button
              onClick={() => dispatch({ type: "RESTART" })}
              className="flex-1 bg-gray-700 hover:bg-gray-600 text-white text-sm font-semibold py-2 px-3 rounded transition-colors cursor-pointer"
            >
              Restart
            </button>
          </div>
        )}
      </div>
    </div>
    // /[worker-ants] generated by AI Agent (2026-03-14 12:33:58)
  );
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:43:24)
