// [worker-ants] generated by AI Agent (2026-03-14 15:54:04)
import { describe, it, expect } from "vitest";
import { toBroadcastState, calculateRankings } from "../broadcast";
import { initGame } from "../../tetris/gameEngine";

describe("toBroadcastState", () => {
  it("converts GameState to BroadcastState", () => {
    const gameState = initGame();
    const broadcast = toBroadcastState(gameState);

    expect(broadcast.score).toBe(0);
    expect(broadcast.level).toBe(0);
    expect(broadcast.linesCleared).toBe(0);
    expect(broadcast.isGameOver).toBe(false);
    expect(broadcast.isPaused).toBe(true);
    expect(broadcast.board).toHaveLength(22);
    expect(broadcast.board[0]).toHaveLength(10);
  });

  it("converts empty cells to null", () => {
    const gameState = initGame();
    const broadcast = toBroadcastState(gameState);

    // All board cells should be null (empty) initially (except where piece spawns)
    const bottomRow = broadcast.board[21];
    expect(bottomRow.every((cell) => cell === null)).toBe(true);
  });

  it("includes activePiece when not game over", () => {
    const gameState = { ...initGame(), isStarted: true, isPaused: false };
    const broadcast = toBroadcastState(gameState);

    expect(broadcast.activePiece).not.toBeNull();
    expect(broadcast.activePiece!.type).toBeDefined();
    expect(broadcast.activePiece!.shape).toBeDefined();
    expect(broadcast.activePiece!.row).toBeDefined();
    expect(broadcast.activePiece!.col).toBeDefined();
  });

  it("sets activePiece to null when game over", () => {
    const gameState = { ...initGame(), isGameOver: true };
    const broadcast = toBroadcastState(gameState);

    expect(broadcast.activePiece).toBeNull();
  });
// [worker-ants] generated by AI Agent (2026-03-14 16:40:41)

  it("includes activePiece when paused", () => {
    const gameState = { ...initGame(), isStarted: true, isPaused: true, isGameOver: false };
    const broadcast = toBroadcastState(gameState);

    expect(broadcast.activePiece).not.toBeNull();
  });
// /[worker-ants] generated by AI Agent (2026-03-14 16:40:41)
});

describe("calculateRankings", () => {
  it("ranks players by score descending", () => {
    const players = [
      { id: "a", name: "Alice", score: 500 },
      { id: "b", name: "Bob", score: 1000 },
      { id: "c", name: "Carol", score: 750 },
    ];

    const rankings = calculateRankings(players);

    expect(rankings).toHaveLength(3);
    expect(rankings[0]).toEqual({
      playerId: "b",
      name: "Bob",
      score: 1000,
      rank: 1,
    });
    expect(rankings[1]).toEqual({
      playerId: "c",
      name: "Carol",
      score: 750,
      rank: 2,
    });
    expect(rankings[2]).toEqual({
      playerId: "a",
      name: "Alice",
      score: 500,
      rank: 3,
    });
  });

  it("handles single player", () => {
    const players = [{ id: "a", name: "Alice", score: 100 }];
    const rankings = calculateRankings(players);

    expect(rankings).toHaveLength(1);
    expect(rankings[0].rank).toBe(1);
  });

  // [worker-ants] generated by AI Agent (2026-03-14 16:40:41)
  it("handles tied scores with same rank", () => {
  // /[worker-ants] generated by AI Agent (2026-03-14 16:40:41)
    const players = [
      { id: "a", name: "Alice", score: 500 },
      { id: "b", name: "Bob", score: 500 },
    ];

    const rankings = calculateRankings(players);
    expect(rankings).toHaveLength(2);
    expect(rankings[0].rank).toBe(1);
    // [worker-ants] generated by AI Agent (2026-03-14 16:40:41)
    expect(rankings[1].rank).toBe(1);
  });

  it("handles tied scores with mixed ranks", () => {
    const players = [
      { id: "a", name: "Alice", score: 1000 },
      { id: "b", name: "Bob", score: 500 },
      { id: "c", name: "Carol", score: 500 },
      { id: "d", name: "Dave", score: 100 },
    ];

    const rankings = calculateRankings(players);
    expect(rankings[0].rank).toBe(1);
    expect(rankings[1].rank).toBe(2);
    expect(rankings[2].rank).toBe(2);
    expect(rankings[3].rank).toBe(4);
    // /[worker-ants] generated by AI Agent (2026-03-14 16:40:41)
  });

  it("handles max 5 players", () => {
    const players = [
      { id: "a", name: "P1", score: 100 },
      { id: "b", name: "P2", score: 200 },
      { id: "c", name: "P3", score: 300 },
      { id: "d", name: "P4", score: 400 },
      { id: "e", name: "P5", score: 500 },
    ];

    const rankings = calculateRankings(players);
    expect(rankings).toHaveLength(5);
    expect(rankings[0].rank).toBe(1);
    expect(rankings[0].score).toBe(500);
    expect(rankings[4].rank).toBe(5);
    expect(rankings[4].score).toBe(100);
  });
// [worker-ants] generated by AI Agent (2026-03-14 16:40:41)

  it("does not mutate input array", () => {
    const players = [
      { id: "a", name: "Alice", score: 200 },
      { id: "b", name: "Bob", score: 100 },
    ];
    const copy = [...players];
    calculateRankings(players);
    expect(players).toEqual(copy);
  });

  it("handles empty array", () => {
    const rankings = calculateRankings([]);
    expect(rankings).toEqual([]);
  });
// /[worker-ants] generated by AI Agent (2026-03-14 16:40:41)
});

// /[worker-ants] generated by AI Agent (2026-03-14 15:54:04)
