// [worker-ants] generated by AI Agent (2026-03-15 00:55:05)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
import { describe, it, expect } from "vitest";
import { isValidWsUrl } from "../validation";
import { sanitizeName } from "../sanitize.mjs";

describe("isValidWsUrl", () => {
  it("accepts ws:// URLs", () => {
    expect(isValidWsUrl("ws://192.168.0.1:3000/ws")).toBe(true);
    expect(isValidWsUrl("ws://localhost:3000/ws")).toBe(true);
  });

  it("accepts wss:// URLs", () => {
    expect(isValidWsUrl("wss://example.com/ws")).toBe(true);
    expect(isValidWsUrl("wss://192.168.0.1:3000/ws")).toBe(true);
  });

  it("rejects http:// URLs", () => {
    expect(isValidWsUrl("http://localhost:3000")).toBe(false);
    expect(isValidWsUrl("https://example.com")).toBe(false);
  });

  it("rejects ftp:// URLs", () => {
    expect(isValidWsUrl("ftp://example.com")).toBe(false);
  });

  it("rejects bare IP addresses", () => {
    expect(isValidWsUrl("192.168.0.1:3000")).toBe(false);
  });

  it("rejects empty strings", () => {
    expect(isValidWsUrl("")).toBe(false);
  });

  it("rejects malformed URLs", () => {
    expect(isValidWsUrl("not-a-url")).toBe(false);
    expect(isValidWsUrl("://missing-protocol")).toBe(false);
  });
});

describe("sanitizeName", () => {
  it("returns fallback for empty string", () => {
    expect(sanitizeName("", "Host")).toBe("Host");
  });

  it("returns fallback for whitespace-only string", () => {
    expect(sanitizeName("   ", "Guest")).toBe("Guest");
  });

  it("returns fallback for non-string input", () => {
    expect(sanitizeName(null, "Host")).toBe("Host");
    expect(sanitizeName(undefined, "Host")).toBe("Host");
    expect(sanitizeName(123, "Host")).toBe("Host");
  });

  it("trims whitespace from valid names", () => {
    expect(sanitizeName("  Alice  ", "Host")).toBe("Alice");
  });

  it("truncates names exceeding max length", () => {
    expect(sanitizeName("A".repeat(20), "Host")).toBe("A".repeat(16));
  });

  it("respects custom max length", () => {
    expect(sanitizeName("Hello World", "Host", 5)).toBe("Hello");
  });

  it("preserves valid names within length", () => {
    expect(sanitizeName("Bob", "Host")).toBe("Bob");
  });
});
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

// /[worker-ants] generated by AI Agent (2026-03-15 00:55:05)
