// [worker-ants] generated by AI Agent (2026-03-14 15:50:29)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import type {
  BroadcastState,
  PlayerInfo,
  RankingEntry,
  ServerMessage,
  MultiplayerPhase,
} from "@/lib/multiplayer/types";

// [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
const BROADCAST_INTERVAL_MS = 100; // 10fps throttle

// /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
interface UseMultiplayerOptions {
  role: "host" | "guest";
  playerName: string;
  endpoint?: string;
  password?: string;
}

interface UseMultiplayerReturn {
  phase: MultiplayerPhase;
  playerId: string | null;
  players: PlayerInfo[];
  // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  isHost: boolean;
  // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  opponentStates: Record<string, BroadcastState>;
  rankings: RankingEntry[] | null;
  sessionInfo: { password: string; endpoint: string } | null;
  error: string | null;
  isConnected: boolean;
  connect: () => void;
  startGame: () => void;
  sendState: (state: BroadcastState) => void;
  disconnect: () => void;
}

export function useMultiplayer(
  options: UseMultiplayerOptions
): UseMultiplayerReturn {
  const [phase, setPhase] = useState<MultiplayerPhase>("lobby");
  const [playerId, setPlayerId] = useState<string | null>(null);
  const [players, setPlayers] = useState<PlayerInfo[]>([]);
  // [worker-ants] generated by AI Agent (2026-03-15 00:53:31)
  const [opponentStates, setOpponentStates] = useState<
  // /[worker-ants] generated by AI Agent (2026-03-15 00:53:31)
    Record<string, BroadcastState>
  >({});
  const [rankings, setRankings] = useState<RankingEntry[] | null>(null);
  const [sessionInfo, setSessionInfo] = useState<{
    password: string;
    endpoint: string;
  } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isConnected, setIsConnected] = useState(false);

  const wsRef = useRef<WebSocket | null>(null);
  // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  // WebSocket callbacks reference the latest playerId via ref (avoids stale closure)
  // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  const playerIdRef = useRef<string | null>(null);
  const throttleRef = useRef<number>(0);
  // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  // Keep latest options in a ref so connect callback doesn't need to re-create on every render
  // [worker-ants] generated by AI Agent (2026-03-15 01:01:55)
  // [worker-ants] generated by AI Agent (2026-03-16 20:17:53)
  const optionsRef = useRef(options);
  optionsRef.current = options;
  // /[worker-ants] generated by AI Agent (2026-03-16 20:17:53)
  // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  // /[worker-ants] generated by AI Agent (2026-03-15 01:01:55)

  const handleMessage = useCallback(
    (event: MessageEvent) => {
      // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
      let msg: ServerMessage;
      try {
        msg = JSON.parse(event.data);
      } catch {
        return;
      }

      if (!msg || typeof msg.type !== "string") return;
      // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)

      switch (msg.type) {
        case "session_created":
          setSessionInfo({ password: msg.password, endpoint: msg.endpoint });
          setPlayerId(msg.playerId);
          playerIdRef.current = msg.playerId;
          // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
          setPlayers([
            { id: msg.playerId, name: optionsRef.current.playerName, isHost: true },
          ]);
          // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
          break;

        case "join_result":
          if (msg.success) {
            setPlayerId(msg.playerId!);
            playerIdRef.current = msg.playerId!;
            setPlayers(msg.players!);
          } else {
            setError(msg.error || "Failed to join");
          }
          break;

        case "player_joined":
          setPlayers(msg.players);
          break;

        case "player_left":
          setPlayers(msg.players);
          setOpponentStates((prev) => {
            const next = { ...prev };
            delete next[msg.playerId];
            return next;
          });
          break;

        // [worker-ants] generated by AI Agent (2026-03-15 00:53:46)
        // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
        case "host_transferred":
          setPlayers(msg.players);
          break;

        // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
        case "error":
          setError(msg.error);
          break;
        // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

        // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
        case "game_started":
        // /[worker-ants] generated by AI Agent (2026-03-15 00:53:46)
          setPhase("playing");
          break;

        case "state_broadcast": {
          const myId = playerIdRef.current;
          // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
          if (myId) {
            // Server now sends only the changed player's state — merge incrementally
            setOpponentStates((prev) => {
              const next = { ...prev };
              // [worker-ants] generated by AI Agent (2026-03-15 00:55:43)
              for (const [id, state] of Object.entries(msg.states)) {
                if (id !== myId && state) {
                  next[id] = state;
                }
              }
              // /[worker-ants] generated by AI Agent (2026-03-15 00:55:43)
              return next;
            });
          }
          // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
          break;
        }

        case "round_end":
          setRankings(msg.rankings);
          setPhase("result");
          break;
      }
    },
    // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    []
    // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  );

  // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  // Use ref to keep handler fresh for WebSocket without re-assigning
  // [worker-ants] generated by AI Agent (2026-03-15 01:02:15)
  // [worker-ants] generated by AI Agent (2026-03-16 20:18:01)
  const handleMessageRef = useRef(handleMessage);
  handleMessageRef.current = handleMessage;
  // /[worker-ants] generated by AI Agent (2026-03-16 20:18:01)

  const connect = useCallback(() => {
  // /[worker-ants] generated by AI Agent (2026-03-15 01:02:15)
    // Prevent duplicate connections
    if (wsRef.current) return;

  // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    setError(null);

    // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    const { role, playerName, endpoint, password } = optionsRef.current;

    const wsUrl =
      role === "host"
        ? `ws://${window.location.hostname}:${window.location.port}/ws`
        : endpoint!;
    // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)

    const ws = new WebSocket(wsUrl);
    wsRef.current = ws;

    ws.onopen = () => {
      setIsConnected(true);
      // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
      if (role === "host") {
      // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
        ws.send(
          JSON.stringify({
            type: "create_session",
            // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
            playerName,
            // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
          })
        );
      } else {
        ws.send(
          JSON.stringify({
            type: "join_session",
            // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
            password,
            playerName,
            // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
          })
        );
      }
    };

    // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    // Use ref wrapper to always invoke the latest handler
    ws.onmessage = (e) => handleMessageRef.current(e);
    // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)

    // [worker-ants] generated by AI Agent (2026-03-16 20:17:28)
    ws.onclose = () => {
      setIsConnected(false);
      // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
      wsRef.current = null;
      // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
      setPhase("lobby");
      setPlayers([]);
      setOpponentStates({});
    };
    // /[worker-ants] generated by AI Agent (2026-03-16 20:17:28)

    ws.onerror = () => {
      setError("Connection failed. Is the server running?");
      setIsConnected(false);
    };
  // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
  }, []);
  // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)

  const startGame = useCallback(() => {
    wsRef.current?.send(JSON.stringify({ type: "start_game" }));
  }, []);

  const sendState = useCallback((state: BroadcastState) => {
    const now = Date.now();
    // Always send game over state; throttle others to 10fps
    // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    if (!state.isGameOver && now - throttleRef.current < BROADCAST_INTERVAL_MS)
      return;
    // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    throttleRef.current = now;

    if (wsRef.current?.readyState === WebSocket.OPEN) {
      wsRef.current.send(JSON.stringify({ type: "state_update", state }));
    }
  }, []);

  const disconnect = useCallback(() => {
    // [worker-ants] generated by AI Agent (2026-03-16 20:17:44)
    wsRef.current?.close();
    wsRef.current = null;
    setIsConnected(false);
    setPlayerId(null);
    setPhase("lobby");
    // /[worker-ants] generated by AI Agent (2026-03-16 20:17:44)
    setPlayers([]);
    setOpponentStates({});
    setRankings(null);
    setSessionInfo(null);
    setError(null);
  }, []);

  // [worker-ants] generated by AI Agent (2026-03-15 00:54:02)
  // [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
  // Derive isHost from players list — single source of truth
  // [worker-ants] generated by AI Agent (2026-03-16 20:17:18)
  const isHost = playerId
    ? players.some((p) => p.id === playerId && p.isHost)
    : false;
  // /[worker-ants] generated by AI Agent (2026-03-16 20:17:18)
  // /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

  useEffect(() => {
    return () => {
      wsRef.current?.close();
      wsRef.current = null;
    };
  }, []);

  return {
  // /[worker-ants] generated by AI Agent (2026-03-15 00:54:02)
    phase,
    playerId,
    players,
    // [worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    isHost,
    // /[worker-ants] generated by AI Agent (2026-03-14 16:38:16)
    opponentStates,
    rankings,
    sessionInfo,
    error,
    isConnected,
    connect,
    startGame,
    sendState,
    disconnect,
  };
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:50:29)
