// [worker-ants] generated by AI Agent (2026-03-14 15:50:29)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import type {
  BroadcastState,
  PlayerInfo,
  RankingEntry,
  ServerMessage,
  MultiplayerPhase,
} from "@/lib/multiplayer/types";

interface UseMultiplayerOptions {
  role: "host" | "guest";
  playerName: string;
  endpoint?: string;
  password?: string;
}

interface UseMultiplayerReturn {
  phase: MultiplayerPhase;
  playerId: string | null;
  players: PlayerInfo[];
  opponentStates: Record<string, BroadcastState>;
  rankings: RankingEntry[] | null;
  sessionInfo: { password: string; endpoint: string } | null;
  error: string | null;
  isConnected: boolean;
  connect: () => void;
  startGame: () => void;
  sendState: (state: BroadcastState) => void;
  disconnect: () => void;
}

export function useMultiplayer(
  options: UseMultiplayerOptions
): UseMultiplayerReturn {
  const [phase, setPhase] = useState<MultiplayerPhase>("lobby");
  const [playerId, setPlayerId] = useState<string | null>(null);
  const [players, setPlayers] = useState<PlayerInfo[]>([]);
  const [opponentStates, setOpponentStates] = useState<
    Record<string, BroadcastState>
  >({});
  const [rankings, setRankings] = useState<RankingEntry[] | null>(null);
  const [sessionInfo, setSessionInfo] = useState<{
    password: string;
    endpoint: string;
  } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isConnected, setIsConnected] = useState(false);

  const wsRef = useRef<WebSocket | null>(null);
  const playerIdRef = useRef<string | null>(null);
  const throttleRef = useRef<number>(0);

  const handleMessage = useCallback(
    (event: MessageEvent) => {
      const msg: ServerMessage = JSON.parse(event.data);

      switch (msg.type) {
        case "session_created":
          setSessionInfo({ password: msg.password, endpoint: msg.endpoint });
          setPlayerId(msg.playerId);
          playerIdRef.current = msg.playerId;
          setPlayers([
            { id: msg.playerId, name: options.playerName, isHost: true },
          ]);
          break;

        case "join_result":
          if (msg.success) {
            setPlayerId(msg.playerId!);
            playerIdRef.current = msg.playerId!;
            setPlayers(msg.players!);
          } else {
            setError(msg.error || "Failed to join");
          }
          break;

        case "player_joined":
          setPlayers(msg.players);
          break;

        case "player_left":
          setPlayers(msg.players);
          setOpponentStates((prev) => {
            const next = { ...prev };
            delete next[msg.playerId];
            return next;
          });
          break;

        case "game_started":
          setPhase("playing");
          break;

        case "state_broadcast": {
          const myId = playerIdRef.current;
          if (myId) {
            const others: Record<string, BroadcastState> = {};
            for (const [id, state] of Object.entries(msg.states)) {
              if (id !== myId) {
                others[id] = state;
              }
            }
            setOpponentStates(others);
          }
          break;
        }

        case "round_end":
          setRankings(msg.rankings);
          setPhase("result");
          break;
      }
    },
    [options.playerName]
  );

  const connect = useCallback(() => {
    setError(null);

    const wsUrl =
      options.role === "host"
        ? `ws://${window.location.hostname}:${window.location.port}/ws`
        : options.endpoint!;

    const ws = new WebSocket(wsUrl);
    wsRef.current = ws;

    ws.onopen = () => {
      setIsConnected(true);
      if (options.role === "host") {
        ws.send(
          JSON.stringify({
            type: "create_session",
            playerName: options.playerName,
          })
        );
      } else {
        ws.send(
          JSON.stringify({
            type: "join_session",
            password: options.password,
            playerName: options.playerName,
          })
        );
      }
    };

    ws.onmessage = handleMessage;

    ws.onclose = () => {
      setIsConnected(false);
    };

    ws.onerror = () => {
      setError("Connection failed. Is the server running?");
      setIsConnected(false);
    };
  }, [options, handleMessage]);

  const startGame = useCallback(() => {
    wsRef.current?.send(JSON.stringify({ type: "start_game" }));
  }, []);

  const sendState = useCallback((state: BroadcastState) => {
    const now = Date.now();
    // Always send game over state; throttle others to 10fps
    if (!state.isGameOver && now - throttleRef.current < 100) return;
    throttleRef.current = now;

    if (wsRef.current?.readyState === WebSocket.OPEN) {
      wsRef.current.send(JSON.stringify({ type: "state_update", state }));
    }
  }, []);

  const disconnect = useCallback(() => {
    wsRef.current?.close();
    wsRef.current = null;
    setIsConnected(false);
    setPhase("lobby");
    setPlayers([]);
    setOpponentStates({});
    setRankings(null);
    setSessionInfo(null);
    setError(null);
  }, []);

  useEffect(() => {
    return () => {
      wsRef.current?.close();
    };
  }, []);

  return {
    phase,
    playerId,
    players,
    opponentStates,
    rankings,
    sessionInfo,
    error,
    isConnected,
    connect,
    startGame,
    sendState,
    disconnect,
  };
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:50:29)
