// [worker-ants] generated by AI Agent (2026-03-14 15:53:24)
// [worker-ants] generated by AI Agent (2026-03-14 11:43:30)
import GameApp from "./components/GameApp";
// /[worker-ants] generated by AI Agent (2026-03-14 11:43:30)

export default function Home() {
  return (
    // [worker-ants] generated by AI Agent (2026-03-14 11:43:30)
    <div className="min-h-screen bg-gray-900 flex flex-col items-center justify-center p-4">
      <h1 className="text-white text-3xl font-bold mb-6 tracking-wider">TETRIS</h1>
      <GameApp />
    </div>
    // /[worker-ants] generated by AI Agent (2026-03-14 11:43:30)
  );
}
// /[worker-ants] generated by AI Agent (2026-03-14 15:53:24)
