// [worker-ants] generated by AI Agent (2026-03-14 15:49:44)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
import { GameState } from "../tetris/types";
import { BroadcastState, RankingEntry } from "./types";

/** Convert full GameState to condensed BroadcastState for network transmission */
export function toBroadcastState(state: GameState): BroadcastState {
  return {
    board: state.board.map((row) =>
      row.map((cell) => (cell.filled ? cell.color : null))
    ),
    activePiece: state.isGameOver
      ? null
      : {
          type: state.activePiece.type,
          shape: state.activePiece.shape,
          row: state.activePiece.row,
          col: state.activePiece.col,
        },
    score: state.score,
    level: state.level,
    linesCleared: state.linesCleared,
    isGameOver: state.isGameOver,
    isPaused: state.isPaused,
  };
}

/** Calculate rankings from player states, sorted by score descending */
export function calculateRankings(
  players: { id: string; name: string; score: number }[]
): RankingEntry[] {
  return players
    .sort((a, b) => b.score - a.score)
    .map((entry, index) => ({
      playerId: entry.id,
      name: entry.name,
      score: entry.score,
      rank: index + 1,
    }));
}
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:49:44)
