// [worker-ants] generated by AI Agent (2026-03-14 16:35:03)
// [worker-ants] generated by AI Agent (2026-03-14 15:49:44)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:46)
import { GameState } from "../tetris/types";
import { BroadcastState } from "./types";
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
export { calculateRankings } from "./ranking.mjs";
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:46)

/** Convert full GameState to condensed BroadcastState for network transmission */
export function toBroadcastState(state: GameState): BroadcastState {
  return {
    board: state.board.map((row) =>
      row.map((cell) => (cell.filled ? cell.color : null))
    ),
    activePiece: state.isGameOver
      ? null
      : {
          type: state.activePiece.type,
          shape: state.activePiece.shape,
          row: state.activePiece.row,
          col: state.activePiece.col,
        },
    score: state.score,
    level: state.level,
    linesCleared: state.linesCleared,
    isGameOver: state.isGameOver,
    isPaused: state.isPaused,
  };
}

// [worker-ants] generated by AI Agent (2026-03-15 00:51:18)
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)
// /[worker-ants] generated by AI Agent (2026-03-15 00:51:18)

// /[worker-ants] generated by AI Agent (2026-03-14 15:49:44)
// /[worker-ants] generated by AI Agent (2026-03-14 16:35:03)
