// [worker-ants] generated by AI Agent (2026-03-15 00:50:29)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
/**
 * Calculate rankings from player states, sorted by score descending.
 * Tied scores receive the same rank (standard competition ranking: 1-2-2-4).
 * @param {Array<{id: string, name: string, score: number}>} players
 * @returns {Array<{playerId: string, name: string, score: number, rank: number}>}
 */
export function calculateRankings(players) {
  const sorted = [...players].sort((a, b) => b.score - a.score);
  let currentRank = 1;
  return sorted.map((entry, index) => {
    if (index > 0 && entry.score < sorted[index - 1].score) {
      currentRank = index + 1;
    }
    return {
      playerId: entry.id,
      name: entry.name,
      score: entry.score,
      rank: currentRank,
    };
  });
}
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

// /[worker-ants] generated by AI Agent (2026-03-15 00:50:29)
