// [worker-ants] generated by AI Agent (2026-03-15 00:50:33)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
const DEFAULT_MAX_LENGTH = 16;

/** Validate and sanitize player name */
export function sanitizeName(name, fallback, maxLength = DEFAULT_MAX_LENGTH) {
  if (typeof name !== "string" || !name.trim()) return fallback;
  return name.trim().slice(0, maxLength);
}
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

// /[worker-ants] generated by AI Agent (2026-03-15 00:50:33)
