// [worker-ants] generated by AI Agent (2026-03-14 15:49:39)
// [worker-ants] generated by AI Agent (2026-03-14 16:00:00)
import { PieceType } from "../tetris/types";

export const MAX_PLAYERS = 5;

/** Condensed game state for network broadcast */
export interface BroadcastState {
  board: (string | null)[][];
  activePiece: {
    type: PieceType;
    shape: number[][];
    row: number;
    col: number;
  } | null;
  score: number;
  level: number;
  linesCleared: number;
  isGameOver: boolean;
  isPaused: boolean;
}

export interface PlayerInfo {
  id: string;
  name: string;
  isHost: boolean;
}

export interface RankingEntry {
  playerId: string;
  name: string;
  score: number;
  rank: number;
}

// Client → Server messages
export type ClientMessage =
  | { type: "create_session"; playerName: string }
  | { type: "join_session"; password: string; playerName: string }
  | { type: "start_game" }
  | { type: "state_update"; state: BroadcastState };

// [worker-ants] generated by AI Agent (2026-03-14 16:36:02)
// Server → Client messages
export type ServerMessage =
  | { type: "session_created"; password: string; endpoint: string; playerId: string }
  | { type: "join_result"; success: boolean; error?: string; playerId?: string; players?: PlayerInfo[] }
  | { type: "player_joined"; player: PlayerInfo; players: PlayerInfo[] }
  | { type: "player_left"; playerId: string; players: PlayerInfo[] }
  | { type: "host_transferred"; newHostId: string; players: PlayerInfo[] }
  | { type: "game_started" }
  // [worker-ants] generated by AI Agent (2026-03-15 00:50:51)
  | { type: "state_broadcast"; states: Partial<Record<string, BroadcastState>> }
  | { type: "round_end"; rankings: RankingEntry[] }
  | { type: "error"; error: string };
  // /[worker-ants] generated by AI Agent (2026-03-15 00:50:51)
// /[worker-ants] generated by AI Agent (2026-03-14 16:36:02)

export type MultiplayerPhase = "lobby" | "playing" | "result";

export type GameConfig =
  | { mode: "single" }
  | { mode: "multiplayer"; role: "host"; playerName: string }
  | { mode: "multiplayer"; role: "guest"; playerName: string; endpoint: string; password: string };
// /[worker-ants] generated by AI Agent (2026-03-14 16:00:00)

// /[worker-ants] generated by AI Agent (2026-03-14 15:49:39)
