// [worker-ants] generated by AI Agent (2026-03-15 00:50:34)
// [worker-ants] generated by AI Agent (2026-03-15 00:50:00)
/** Validate that a URL is a valid WebSocket URL (ws: or wss: protocol) */
export function isValidWsUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.protocol === "ws:" || parsed.protocol === "wss:";
  } catch {
    return false;
  }
}
// /[worker-ants] generated by AI Agent (2026-03-15 00:50:00)

// /[worker-ants] generated by AI Agent (2026-03-15 00:50:34)
