// [worker-ants] generated by AI Agent (2026-03-14 11:41:47)
import { BOARD_COLS, BOARD_ROWS } from "./constants";
import { Board, ActivePiece, Cell } from "./types";
import { PIECE_COLORS } from "./tetrominoes";

export function createEmptyBoard(): Board {
  return Array.from({ length: BOARD_ROWS }, () =>
    Array.from({ length: BOARD_COLS }, (): Cell => ({ filled: false, color: "" }))
  );
}

function createEmptyRow(): Cell[] {
  return Array.from({ length: BOARD_COLS }, (): Cell => ({ filled: false, color: "" }));
}

export function placePiece(board: Board, piece: ActivePiece): Board {
  const newBoard = board.map((row) => row.map((cell) => ({ ...cell })));
  const color = PIECE_COLORS[piece.type];

  for (let r = 0; r < piece.shape.length; r++) {
    for (let c = 0; c < piece.shape[r].length; c++) {
      if (!piece.shape[r][c]) continue;
      const boardRow = piece.row + r;
      const boardCol = piece.col + c;
      if (boardRow >= 0 && boardRow < BOARD_ROWS && boardCol >= 0 && boardCol < BOARD_COLS) {
        newBoard[boardRow][boardCol] = { filled: true, color };
      }
    }
  }

  return newBoard;
}

export function clearLines(board: Board): { board: Board; cleared: number } {
  const remaining = board.filter(
    (row) => !row.every((cell) => cell.filled)
  );
  const cleared = BOARD_ROWS - remaining.length;

  if (cleared === 0) return { board, cleared: 0 };

  const emptyRows = Array.from({ length: cleared }, createEmptyRow);
  return { board: [...emptyRows, ...remaining], cleared };
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:41:47)
