// [worker-ants] generated by AI Agent (2026-03-14 11:41:41)
import { BOARD_COLS, BOARD_ROWS } from "./constants";
import { Board, Shape } from "./types";

export function isValidPosition(
  board: Board,
  shape: Shape,
  row: number,
  col: number
): boolean {
  for (let r = 0; r < shape.length; r++) {
    for (let c = 0; c < shape[r].length; c++) {
      if (!shape[r][c]) continue;

      const boardRow = row + r;
      const boardCol = col + c;

      // Check bounds
      if (boardCol < 0 || boardCol >= BOARD_COLS) return false;
      if (boardRow >= BOARD_ROWS) return false;
      // Allow above top (negative rows) for spawning
      if (boardRow < 0) continue;

      // Check occupied
      if (board[boardRow][boardCol].filled) return false;
    }
  }
  return true;
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:41:41)
