// [worker-ants] generated by AI Agent (2026-03-14 11:41:20)
export const BOARD_COLS = 10;
export const BOARD_ROWS = 22; // 2 hidden rows at top
export const VISIBLE_ROWS = 20;
export const CELL_SIZE = 30;

export const CANVAS_WIDTH = BOARD_COLS * CELL_SIZE;
export const CANVAS_HEIGHT = VISIBLE_ROWS * CELL_SIZE;

export const PREVIEW_SIZE = 4;
export const PREVIEW_CELL_SIZE = 30;
export const PREVIEW_CANVAS_SIZE = PREVIEW_SIZE * PREVIEW_CELL_SIZE;

export const SCORING_TABLE: Record<number, number> = {
  1: 100,
  2: 300,
  3: 500,
  4: 800,
};

export const LINES_PER_LEVEL = 10;
export const BASE_DROP_INTERVAL = 800;
export const DROP_INTERVAL_DECREASE = 75;
export const MIN_DROP_INTERVAL = 50;

export const SOFT_DROP_POINTS = 1;
export const HARD_DROP_POINTS = 2;

// /[worker-ants] generated by AI Agent (2026-03-14 11:41:20)
