// [worker-ants] generated by AI Agent (2026-03-14 11:42:26)
import { BOARD_COLS, SOFT_DROP_POINTS, HARD_DROP_POINTS } from "./constants";
import { GameState, ActivePiece, PieceType } from "./types";
import { createEmptyBoard, placePiece, clearLines } from "./board";
import { isValidPosition } from "./collision";
import { tryRotate } from "./rotation";
import { getShape, ALL_PIECE_TYPES } from "./tetrominoes";
import { calculateScore, getLevel } from "./scoring";

function shuffleBag(): PieceType[] {
  const bag = [...ALL_PIECE_TYPES];
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [bag[i], bag[j]] = [bag[j], bag[i]];
  }
  return bag;
}

function drawFromBag(bag: PieceType[]): { piece: PieceType; bag: PieceType[] } {
  if (bag.length === 0) {
    bag = shuffleBag();
  }
  const [piece, ...rest] = bag;
  return { piece, bag: rest };
}

function spawnPiece(type: PieceType): ActivePiece {
  const shape = getShape(type, 0);
  return {
    type,
    shape,
    row: 0,
    col: Math.floor((BOARD_COLS - shape[0].length) / 2),
    rotationIndex: 0,
  };
}

export function initGame(): GameState {
  // [worker-ants] generated by AI Agent (2026-03-15 01:02:00)
  const bag = shuffleBag();
  // /[worker-ants] generated by AI Agent (2026-03-15 01:02:00)
  const { piece: firstType, bag: bag2 } = drawFromBag(bag);
  const { piece: nextType, bag: bag3 } = drawFromBag(bag2);

  return {
    board: createEmptyBoard(),
    activePiece: spawnPiece(firstType),
    nextPiece: nextType,
    bag: bag3,
    score: 0,
    level: 0,
    linesCleared: 0,
// [worker-ants] generated by AI Agent (2026-03-14 12:32:49)
    isGameOver: false,
    isPaused: true,
    isStarted: false,
  };
// /[worker-ants] generated by AI Agent (2026-03-14 12:32:49)
}

function lockAndSpawn(state: GameState): GameState {
  const boardAfterPlace = placePiece(state.board, state.activePiece);
  const { board: boardAfterClear, cleared } = clearLines(boardAfterPlace);

  const newLinesCleared = state.linesCleared + cleared;
  const newLevel = getLevel(newLinesCleared);
  const lineScore = calculateScore(cleared, state.level);
  const newScore = state.score + lineScore;

  const { piece: nextType, bag: newBag } = drawFromBag(state.bag);
  const newActive = spawnPiece(state.nextPiece);

  // Check game over: new piece can't be placed
  const isGameOver = !isValidPosition(boardAfterClear, newActive.shape, newActive.row, newActive.col);

  return {
    ...state,
    board: boardAfterClear,
    activePiece: newActive,
    nextPiece: nextType,
    bag: newBag,
    score: newScore,
    level: newLevel,
    linesCleared: newLinesCleared,
    isGameOver,
  };
}

// [worker-ants] generated by AI Agent (2026-03-14 14:58:08)
export function tick(state: GameState): GameState {
  if (state.isGameOver || state.isPaused || !state.isStarted) return state;
// /[worker-ants] generated by AI Agent (2026-03-14 14:58:08)

  const newRow = state.activePiece.row + 1;
  if (isValidPosition(state.board, state.activePiece.shape, newRow, state.activePiece.col)) {
    return {
      ...state,
      activePiece: { ...state.activePiece, row: newRow },
    };
  }

  // Can't move down → lock
  return lockAndSpawn(state);
}

// [worker-ants] generated by AI Agent (2026-03-14 14:58:22)
export function moveLeft(state: GameState): GameState {
  if (state.isGameOver || state.isPaused || !state.isStarted) return state;
// /[worker-ants] generated by AI Agent (2026-03-14 14:58:22)

  const newCol = state.activePiece.col - 1;
  if (isValidPosition(state.board, state.activePiece.shape, state.activePiece.row, newCol)) {
    return {
      ...state,
      activePiece: { ...state.activePiece, col: newCol },
    };
  }
  return state;
}

// [worker-ants] generated by AI Agent (2026-03-14 14:58:35)
export function moveRight(state: GameState): GameState {
  if (state.isGameOver || state.isPaused || !state.isStarted) return state;
// /[worker-ants] generated by AI Agent (2026-03-14 14:58:35)

  const newCol = state.activePiece.col + 1;
  if (isValidPosition(state.board, state.activePiece.shape, state.activePiece.row, newCol)) {
    return {
      ...state,
      activePiece: { ...state.activePiece, col: newCol },
    };
  }
  return state;
}

// [worker-ants] generated by AI Agent (2026-03-14 14:58:48)
export function softDrop(state: GameState): GameState {
  if (state.isGameOver || state.isPaused || !state.isStarted) return state;
// /[worker-ants] generated by AI Agent (2026-03-14 14:58:48)

  const newRow = state.activePiece.row + 1;
  if (isValidPosition(state.board, state.activePiece.shape, newRow, state.activePiece.col)) {
    return {
      ...state,
      activePiece: { ...state.activePiece, row: newRow },
      score: state.score + SOFT_DROP_POINTS,
    };
  }
  return state;
}

// [worker-ants] generated by AI Agent (2026-03-14 14:59:02)
export function hardDrop(state: GameState): GameState {
  if (state.isGameOver || state.isPaused || !state.isStarted) return state;
// /[worker-ants] generated by AI Agent (2026-03-14 14:59:02)

  let dropRow = state.activePiece.row;
  while (isValidPosition(state.board, state.activePiece.shape, dropRow + 1, state.activePiece.col)) {
    dropRow++;
  }

  const cellsDropped = dropRow - state.activePiece.row;
  const stateWithDrop = {
    ...state,
    activePiece: { ...state.activePiece, row: dropRow },
    score: state.score + cellsDropped * HARD_DROP_POINTS,
  };

  return lockAndSpawn(stateWithDrop);
}

// [worker-ants] generated by AI Agent (2026-03-14 14:59:16)
export function rotate(state: GameState, direction: 1 | -1): GameState {
  if (state.isGameOver || state.isPaused || !state.isStarted) return state;
// /[worker-ants] generated by AI Agent (2026-03-14 14:59:16)

  const rotated = tryRotate(state.board, state.activePiece, direction);
  if (rotated) {
    return { ...state, activePiece: rotated };
  }
  return state;
}

// [worker-ants] generated by AI Agent (2026-03-14 14:59:41)
// [worker-ants] generated by AI Agent (2026-03-14 12:33:00)
/** Transitions game from idle to running. No-op if already started or game is over. */
export function startGame(state: GameState): GameState {
  if (state.isStarted || state.isGameOver) return state;
  return { ...state, isStarted: true, isPaused: false };
}

/** Toggles pause/resume. No-op if game hasn't started or is over. */
export function togglePause(state: GameState): GameState {
  if (state.isGameOver || !state.isStarted) return state;
  return { ...state, isPaused: !state.isPaused };
}
// /[worker-ants] generated by AI Agent (2026-03-14 12:33:00)
// /[worker-ants] generated by AI Agent (2026-03-14 14:59:41)

// [worker-ants] generated by AI Agent (2026-03-16 20:17:17)
/** Returns the lowest valid row for the active piece (ghost/shadow position). */
export function getGhostRow(state: GameState): number {
// /[worker-ants] generated by AI Agent (2026-03-16 20:17:17)
  let ghostRow = state.activePiece.row;
  while (isValidPosition(state.board, state.activePiece.shape, ghostRow + 1, state.activePiece.col)) {
    ghostRow++;
  }
  return ghostRow;
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:42:26)
