// [worker-ants] generated by AI Agent (2026-03-14 15:00:01)
// [worker-ants] generated by AI Agent (2026-03-14 14:59:50)
import { GameState, GameAction } from "./types";
import {
  initGame,
  startGame,
  tick,
  moveLeft,
  moveRight,
  softDrop,
  hardDrop,
  rotate,
  togglePause,
} from "./gameEngine";

export function gameReducer(state: GameState, action: GameAction): GameState {
  switch (action.type) {
    case "TICK":
      return tick(state);
    case "MOVE_LEFT":
      return moveLeft(state);
    case "MOVE_RIGHT":
      return moveRight(state);
    case "SOFT_DROP":
      return softDrop(state);
    case "HARD_DROP":
      return hardDrop(state);
    case "ROTATE_CW":
      return rotate(state, 1);
    case "ROTATE_CCW":
      return rotate(state, -1);
    case "TOGGLE_PAUSE":
      return togglePause(state);
    case "RESTART": {
      const fresh = initGame();
      return { ...fresh, isStarted: true, isPaused: false };
    }
    case "START":
      return startGame(state);
    default:
      return state;
  }
}
// /[worker-ants] generated by AI Agent (2026-03-14 14:59:50)

// /[worker-ants] generated by AI Agent (2026-03-14 15:00:01)
