// [worker-ants] generated by AI Agent (2026-03-14 11:41:53)
import { Board, ActivePiece } from "./types";
import { getShape } from "./tetrominoes";
import { isValidPosition } from "./collision";

const STANDARD_OFFSETS = [
  { dr: 0, dc: -1 },
  { dr: 0, dc: 1 },
  { dr: -1, dc: 0 },
  { dr: 1, dc: 0 },
];

const I_EXTRA_OFFSETS = [
  { dr: 0, dc: -2 },
  { dr: 0, dc: 2 },
];

export function tryRotate(
  board: Board,
  piece: ActivePiece,
  direction: 1 | -1
): ActivePiece | null {
  const newRotation = ((piece.rotationIndex + direction) % 4 + 4) % 4;
  const newShape = getShape(piece.type, newRotation);

  // Try base position
  if (isValidPosition(board, newShape, piece.row, piece.col)) {
    return { ...piece, shape: newShape, rotationIndex: newRotation };
  }

  // Try wall kick offsets
  const offsets = piece.type === "I"
    ? [...STANDARD_OFFSETS, ...I_EXTRA_OFFSETS]
    : STANDARD_OFFSETS;

  for (const { dr, dc } of offsets) {
    if (isValidPosition(board, newShape, piece.row + dr, piece.col + dc)) {
      return {
        ...piece,
        shape: newShape,
        rotationIndex: newRotation,
        row: piece.row + dr,
        col: piece.col + dc,
      };
    }
  }

  return null; // Rotation not possible
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:41:53)
