// [worker-ants] generated by AI Agent (2026-03-14 11:41:56)
import {
  SCORING_TABLE,
  LINES_PER_LEVEL,
  BASE_DROP_INTERVAL,
  DROP_INTERVAL_DECREASE,
  MIN_DROP_INTERVAL,
} from "./constants";

export function calculateScore(
  linesCleared: number,
  level: number
): number {
  if (linesCleared === 0) return 0;
  const base = SCORING_TABLE[linesCleared] ?? 0;
  return base * (level + 1);
}

export function getLevel(totalLinesCleared: number): number {
  return Math.floor(totalLinesCleared / LINES_PER_LEVEL);
}

export function getDropInterval(level: number): number {
  return Math.max(
    BASE_DROP_INTERVAL - level * DROP_INTERVAL_DECREASE,
    MIN_DROP_INTERVAL
  );
}

// /[worker-ants] generated by AI Agent (2026-03-14 11:41:56)
