// [worker-ants] generated by AI Agent (2026-03-14 11:41:24)
export type PieceType = "I" | "O" | "T" | "S" | "Z" | "J" | "L";

export interface Cell {
  filled: boolean;
  color: string;
}

export type Board = Cell[][];

export type Shape = number[][];

export interface ActivePiece {
  type: PieceType;
  shape: Shape;
  row: number;
  col: number;
  rotationIndex: number;
}

export interface GameState {
  board: Board;
  activePiece: ActivePiece;
  nextPiece: PieceType;
  bag: PieceType[];
  score: number;
  level: number;
  linesCleared: number;
  isGameOver: boolean;
  isPaused: boolean;
}

export type GameAction =
  | { type: "TICK" }
  | { type: "MOVE_LEFT" }
  | { type: "MOVE_RIGHT" }
  | { type: "SOFT_DROP" }
  | { type: "HARD_DROP" }
  | { type: "ROTATE_CW" }
  | { type: "ROTATE_CCW" }
  | { type: "TOGGLE_PAUSE" }
  | { type: "RESTART" };

// /[worker-ants] generated by AI Agent (2026-03-14 11:41:24)
