// [worker-ants] generated by AI Agent (2026-03-14 14:57:06)
// [worker-ants] generated by AI Agent (2026-03-14 12:32:39)
export type PieceType = "I" | "O" | "T" | "S" | "Z" | "J" | "L";

export interface Cell {
  filled: boolean;
  color: string;
}

export type Board = Cell[][];

export type Shape = number[][];

export interface ActivePiece {
  type: PieceType;
  shape: Shape;
  row: number;
  col: number;
  rotationIndex: number;
}

// [worker-ants] generated by AI Agent (2026-03-14 14:57:53)
/**
 * Game state transitions:
 *   idle (isStarted=false, isPaused=true) → START → running (isStarted=true, isPaused=false)
 *   running → TOGGLE_PAUSE → paused (isStarted=true, isPaused=true)
 *   paused → TOGGLE_PAUSE → running
 *   running → game over (isGameOver=true)
 *   any → RESTART → running (isStarted=true, isPaused=false)
 */
export interface GameState {
  board: Board;
  activePiece: ActivePiece;
  nextPiece: PieceType;
  bag: PieceType[];
  score: number;
  level: number;
  linesCleared: number;
  isGameOver: boolean;
  isPaused: boolean;
  isStarted: boolean;
}

export type GameAction =
  | { type: "TICK" }
  | { type: "MOVE_LEFT" }
  | { type: "MOVE_RIGHT" }
  | { type: "SOFT_DROP" }
  | { type: "HARD_DROP" }
  | { type: "ROTATE_CW" }
  | { type: "ROTATE_CCW" }
  | { type: "TOGGLE_PAUSE" }
  | { type: "RESTART" }
  | { type: "START" };

// /[worker-ants] generated by AI Agent (2026-03-14 12:32:39)
// /[worker-ants] generated by AI Agent (2026-03-14 14:57:53)
