// [worker-ants] generated by AI Agent (2026-03-16 20:17:44)
import { describe, it, expect } from "vitest";
import { createEmptyBoard, placePiece, clearLines } from "../board";
import { BOARD_ROWS, BOARD_COLS } from "../constants";
import { ActivePiece, Board } from "../types";
import { getShape, PIECE_COLORS } from "../tetrominoes";

describe("createEmptyBoard", () => {
  it("returns board with correct dimensions (BOARD_ROWS x BOARD_COLS)", () => {
    const board = createEmptyBoard();
    expect(board.length).toBe(BOARD_ROWS);
    for (const row of board) {
      expect(row.length).toBe(BOARD_COLS);
    }
  });

  it("all cells are unfilled with empty color", () => {
    const board = createEmptyBoard();
    for (let r = 0; r < BOARD_ROWS; r++) {
      for (let c = 0; c < BOARD_COLS; c++) {
        expect(board[r][c].filled).toBe(false);
        expect(board[r][c].color).toBe("");
      }
    }
  });
});

describe("placePiece", () => {
  it("places piece on board with correct colors", () => {
    const board = createEmptyBoard();
    const piece: ActivePiece = {
      type: "T",
      shape: getShape("T", 0),
      row: 5,
      col: 3,
      rotationIndex: 0,
    };
    const result = placePiece(board, piece);
    const expectedColor = PIECE_COLORS["T"];

    // T shape at rotation 0: [[0,1,0],[1,1,1],[0,0,0]]
    // Filled cells: (5,4), (6,3), (6,4), (6,5)
    expect(result[5][4].filled).toBe(true);
    expect(result[5][4].color).toBe(expectedColor);
    expect(result[6][3].filled).toBe(true);
    expect(result[6][3].color).toBe(expectedColor);
    expect(result[6][4].filled).toBe(true);
    expect(result[6][4].color).toBe(expectedColor);
    expect(result[6][5].filled).toBe(true);
    expect(result[6][5].color).toBe(expectedColor);

    // Unfilled cells within bounding box should remain empty
    expect(result[5][3].filled).toBe(false);
    expect(result[5][5].filled).toBe(false);
  });

  it("does not modify original board (immutability)", () => {
    const board = createEmptyBoard();
    const piece: ActivePiece = {
      type: "O",
      shape: getShape("O", 0),
      row: 5,
      col: 4,
      rotationIndex: 0,
    };
    const result = placePiece(board, piece);

    // Original board should remain empty
    expect(board[5][4].filled).toBe(false);
    expect(board[5][5].filled).toBe(false);
    expect(board[6][4].filled).toBe(false);
    expect(board[6][5].filled).toBe(false);

    // Result should have piece placed
    expect(result[5][4].filled).toBe(true);
    expect(result !== board).toBe(true);
  });

  it("handles piece near right edge", () => {
    const board = createEmptyBoard();
    const piece: ActivePiece = {
      type: "O",
      shape: getShape("O", 0),
      row: 10,
      col: BOARD_COLS - 2,
      rotationIndex: 0,
    };
    const result = placePiece(board, piece);

    expect(result[10][BOARD_COLS - 2].filled).toBe(true);
    expect(result[10][BOARD_COLS - 1].filled).toBe(true);
    expect(result[11][BOARD_COLS - 2].filled).toBe(true);
    expect(result[11][BOARD_COLS - 1].filled).toBe(true);
  });

  it("handles piece near bottom edge", () => {
    const board = createEmptyBoard();
    const piece: ActivePiece = {
      type: "O",
      shape: getShape("O", 0),
      row: BOARD_ROWS - 2,
      col: 4,
      rotationIndex: 0,
    };
    const result = placePiece(board, piece);

    expect(result[BOARD_ROWS - 2][4].filled).toBe(true);
    expect(result[BOARD_ROWS - 1][4].filled).toBe(true);
  });
});

describe("clearLines", () => {
  function fillRow(board: Board, row: number, color = "#ff0000"): void {
    for (let c = 0; c < BOARD_COLS; c++) {
      board[row][c] = { filled: true, color };
    }
  }

  it("returns original board when no lines to clear", () => {
    const board = createEmptyBoard();
    const result = clearLines(board);
    expect(result.board).toBe(board); // same reference
    expect(result.cleared).toBe(0);
  });

  it("clears a single full line", () => {
    const board = createEmptyBoard();
    fillRow(board, BOARD_ROWS - 1);
    const result = clearLines(board);

    expect(result.cleared).toBe(1);
    // Bottom row should now be empty (cleared and new empty row added at top)
    expect(result.board[BOARD_ROWS - 1].every((c) => !c.filled)).toBe(true);
    // Top row should be the new empty row
    expect(result.board[0].every((c) => !c.filled)).toBe(true);
  });

  it("clears two full lines (double)", () => {
    const board = createEmptyBoard();
    fillRow(board, BOARD_ROWS - 1);
    fillRow(board, BOARD_ROWS - 2);
    const result = clearLines(board);

    expect(result.cleared).toBe(2);
    expect(result.board.length).toBe(BOARD_ROWS);
  });

  it("clears three full lines (triple)", () => {
    const board = createEmptyBoard();
    fillRow(board, BOARD_ROWS - 1);
    fillRow(board, BOARD_ROWS - 2);
    fillRow(board, BOARD_ROWS - 3);
    const result = clearLines(board);

    expect(result.cleared).toBe(3);
    expect(result.board.length).toBe(BOARD_ROWS);
  });

  it("clears four full lines (tetris)", () => {
    const board = createEmptyBoard();
    fillRow(board, BOARD_ROWS - 1);
    fillRow(board, BOARD_ROWS - 2);
    fillRow(board, BOARD_ROWS - 3);
    fillRow(board, BOARD_ROWS - 4);
    const result = clearLines(board);

    expect(result.cleared).toBe(4);
    expect(result.board.length).toBe(BOARD_ROWS);
  });

  it("returns correct cleared count", () => {
    const board = createEmptyBoard();
    fillRow(board, BOARD_ROWS - 1);
    // Leave BOARD_ROWS-2 incomplete
    board[BOARD_ROWS - 2][0] = { filled: true, color: "#ff0000" };
    fillRow(board, BOARD_ROWS - 3);

    const result = clearLines(board);
    expect(result.cleared).toBe(2); // rows -1 and -3 cleared, -2 stays
  });

  it("adds empty rows at top after clearing", () => {
    const board = createEmptyBoard();
    fillRow(board, BOARD_ROWS - 1);
    fillRow(board, BOARD_ROWS - 2);

    const result = clearLines(board);
    expect(result.cleared).toBe(2);

    // Top 2 rows should be empty
    for (let r = 0; r < 2; r++) {
      for (let c = 0; c < BOARD_COLS; c++) {
        expect(result.board[r][c].filled).toBe(false);
        expect(result.board[r][c].color).toBe("");
      }
    }
  });

  it("preserves non-full rows in correct order after clearing", () => {
    const board = createEmptyBoard();
    // Place a single block on a non-full row
    board[BOARD_ROWS - 3][5] = { filled: true, color: "#00ff00" };
    // Fill the two rows below it
    fillRow(board, BOARD_ROWS - 2);
    fillRow(board, BOARD_ROWS - 1);

    const result = clearLines(board);
    expect(result.cleared).toBe(2);

    // The partial row should now be at the bottom (shifted down by 0 since it was above cleared rows)
    // After clearing 2 rows from bottom, partial row at BOARD_ROWS-3 shifts to BOARD_ROWS-1
    expect(result.board[BOARD_ROWS - 1][5].filled).toBe(true);
    expect(result.board[BOARD_ROWS - 1][5].color).toBe("#00ff00");
  });
});

// /[worker-ants] generated by AI Agent (2026-03-16 20:17:44)
