// [worker-ants] generated by AI Agent (2026-03-16 20:17:18)
import { describe, it, expect } from "vitest";
import { isValidPosition } from "../collision";
import { createEmptyBoard } from "../board";
import { BOARD_COLS, BOARD_ROWS } from "../constants";
import { getShape } from "../tetrominoes";
import { Board } from "../types";

describe("isValidPosition", () => {
  // I piece horizontal: row 1 of 4x4 grid is [1,1,1,1]
  const I_HORIZONTAL = getShape("I", 0);
  // O piece: 2x2 all filled
  const O_SHAPE = getShape("O", 0);
  // T piece: [[0,1,0],[1,1,1],[0,0,0]]
  const T_SHAPE = getShape("T", 0);

  it("returns true for valid position on empty board", () => {
    const board = createEmptyBoard();
    expect(isValidPosition(board, T_SHAPE, 5, 3)).toBe(true);
  });

  it("returns true for O piece in center of empty board", () => {
    const board = createEmptyBoard();
    expect(isValidPosition(board, O_SHAPE, 5, 4)).toBe(true);
  });

  it("returns true for I piece horizontal in center of empty board", () => {
    const board = createEmptyBoard();
    // I_HORIZONTAL has filled cells at row index 1, cols 0-3
    expect(isValidPosition(board, I_HORIZONTAL, 5, 3)).toBe(true);
  });

  it("returns false when piece extends past left boundary", () => {
    const board = createEmptyBoard();
    // T shape has filled cells at col 0 (row 1). Placing at col=-1 pushes col 0 cell to boardCol=-1
    expect(isValidPosition(board, T_SHAPE, 5, -1)).toBe(false);
  });

  it("returns false when piece extends past right boundary", () => {
    const board = createEmptyBoard();
    // T shape is 3 wide. Placing at col=BOARD_COLS-2 means rightmost filled cell (col index 2) -> boardCol = BOARD_COLS
    expect(isValidPosition(board, T_SHAPE, 5, BOARD_COLS - 2)).toBe(false);
  });

  it("returns false when I piece horizontal extends past right boundary", () => {
    const board = createEmptyBoard();
    // I horizontal has filled cells at cols 0-3 in row 1. col = BOARD_COLS - 3 means col index 3 -> boardCol = BOARD_COLS
    expect(isValidPosition(board, I_HORIZONTAL, 5, BOARD_COLS - 3)).toBe(false);
  });

  it("returns false when piece extends past bottom boundary", () => {
    const board = createEmptyBoard();
    // T shape has filled cells at row indices 0 and 1. Placing at row=BOARD_ROWS-1 means row index 1 -> boardRow=BOARD_ROWS
    expect(isValidPosition(board, T_SHAPE, BOARD_ROWS - 1, 3)).toBe(false);
  });

  it("returns true when piece is partially above top (negative row)", () => {
    const board = createEmptyBoard();
    // T shape: row 0 has [0,1,0], row 1 has [1,1,1]. At row=-1, row 0 is at boardRow=-1 (skipped), row 1 is at boardRow=0 (valid)
    expect(isValidPosition(board, T_SHAPE, -1, 3)).toBe(true);
  });

  it("returns true when I piece is partially above top (negative row)", () => {
    const board = createEmptyBoard();
    // I horizontal: filled cells at shape row 1. At row=-1, boardRow=0 which is valid
    expect(isValidPosition(board, I_HORIZONTAL, -1, 3)).toBe(true);
  });

  it("returns false when piece overlaps with filled cells", () => {
    const board = createEmptyBoard();
    // Fill a cell where T piece would land
    // T at row=5, col=3: filled cells are (5,4), (6,3), (6,4), (6,5)
    board[6][4] = { filled: true, color: "#ff0000" };
    expect(isValidPosition(board, T_SHAPE, 5, 3)).toBe(false);
  });

  it("returns false when O piece overlaps with filled cell", () => {
    const board = createEmptyBoard();
    board[5][4] = { filled: true, color: "#ff0000" };
    // O at row=5, col=4: filled cells at (5,4), (5,5), (6,4), (6,5)
    expect(isValidPosition(board, O_SHAPE, 5, 4)).toBe(false);
  });

  it("returns true when filled cells are adjacent but not overlapping", () => {
    const board = createEmptyBoard();
    // Fill cell just below where T piece lands
    // T at row=5, col=3: bottom filled row is row 6. Fill row 7 instead.
    board[7][4] = { filled: true, color: "#ff0000" };
    expect(isValidPosition(board, T_SHAPE, 5, 3)).toBe(true);
  });

  it("returns false for I piece horizontal extending past left boundary", () => {
    const board = createEmptyBoard();
    // I horizontal: filled at shape row 1, cols 0-3. At col=-1, boardCol for col 0 = -1
    expect(isValidPosition(board, I_HORIZONTAL, 5, -1)).toBe(false);
  });
});

// /[worker-ants] generated by AI Agent (2026-03-16 20:17:18)
