// [worker-ants] generated by AI Agent (2026-03-14 14:57:41)
import { describe, it, expect } from "vitest";
import {
  initGame,
  startGame,
  togglePause,
  tick,
  moveLeft,
  moveRight,
  softDrop,
  hardDrop,
  rotate,
} from "../gameEngine";
import { GameState } from "../types";

function runningState(): GameState {
  return { ...initGame(), isStarted: true, isPaused: false };
}

describe("initGame", () => {
  it("returns state with isStarted: false, isPaused: true, isGameOver: false", () => {
    const state = initGame();
    expect(state.isStarted).toBe(false);
    expect(state.isPaused).toBe(true);
    expect(state.isGameOver).toBe(false);
  });

  it("returns state with score: 0, level: 0, linesCleared: 0", () => {
    const state = initGame();
    expect(state.score).toBe(0);
    expect(state.level).toBe(0);
    expect(state.linesCleared).toBe(0);
  });
});

describe("tick", () => {
  it("does nothing when isGameOver is true (returns same reference)", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = tick(state);
    expect(result).toBe(state);
  });

  it("does nothing when isPaused is true (returns same reference)", () => {
    const state = { ...runningState(), isPaused: true };
    const result = tick(state);
    expect(result).toBe(state);
  });

  it("does nothing when isStarted is false (returns same reference)", () => {
    const state = { ...runningState(), isStarted: false };
    const result = tick(state);
    expect(result).toBe(state);
  });

  it("moves piece down by 1 row when game is running", () => {
    const state = runningState();
    const originalRow = state.activePiece.row;
    const result = tick(state);
    expect(result.activePiece.row).toBe(originalRow + 1);
  });
});

describe("startGame", () => {
  it("sets isStarted: true and isPaused: false from initial state", () => {
    const state = initGame();
    const result = startGame(state);
    expect(result.isStarted).toBe(true);
    expect(result.isPaused).toBe(false);
  });

  it("returns same state if already started", () => {
    const state = runningState();
    const result = startGame(state);
    expect(result).toBe(state);
  });

  it("returns same state if game is over", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = startGame(state);
    expect(result).toBe(state);
  });
});

describe("togglePause", () => {
  it("toggles isPaused when game is started", () => {
    const state = runningState();
    expect(state.isPaused).toBe(false);
    const paused = togglePause(state);
    expect(paused.isPaused).toBe(true);
    const unpaused = togglePause(paused);
    expect(unpaused.isPaused).toBe(false);
  });

  it("does nothing before game starts (isStarted: false)", () => {
    const state = initGame();
    const result = togglePause(state);
    expect(result).toBe(state);
  });

  it("does nothing when game is over", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = togglePause(state);
    expect(result).toBe(state);
  });
});

describe("moveLeft", () => {
  it("does nothing when isPaused (returns same reference)", () => {
    const state = { ...runningState(), isPaused: true };
    const result = moveLeft(state);
    expect(result).toBe(state);
  });

  it("does nothing when isGameOver (returns same reference)", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = moveLeft(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted (returns same reference)", () => {
    const state = { ...runningState(), isStarted: false };
    const result = moveLeft(state);
    expect(result).toBe(state);
  });
});

describe("moveRight", () => {
  it("does nothing when isPaused (returns same reference)", () => {
    const state = { ...runningState(), isPaused: true };
    const result = moveRight(state);
    expect(result).toBe(state);
  });

  it("does nothing when isGameOver (returns same reference)", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = moveRight(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted (returns same reference)", () => {
    const state = { ...runningState(), isStarted: false };
    const result = moveRight(state);
    expect(result).toBe(state);
  });
});

describe("softDrop", () => {
  it("does nothing when isPaused", () => {
    const state = { ...runningState(), isPaused: true };
    const result = softDrop(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted", () => {
    const state = { ...runningState(), isStarted: false };
    const result = softDrop(state);
    expect(result).toBe(state);
  });
});

describe("hardDrop", () => {
  it("does nothing when isPaused", () => {
    const state = { ...runningState(), isPaused: true };
    const result = hardDrop(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted", () => {
    const state = { ...runningState(), isStarted: false };
    const result = hardDrop(state);
    expect(result).toBe(state);
  });
});

describe("rotate", () => {
  it("does nothing when isPaused", () => {
    const state = { ...runningState(), isPaused: true };
    const result = rotate(state, 1);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted", () => {
    const state = { ...runningState(), isStarted: false };
    const result = rotate(state, 1);
    expect(result).toBe(state);
  });
});

// /[worker-ants] generated by AI Agent (2026-03-14 14:57:41)
