// [worker-ants] generated by AI Agent (2026-03-14 14:57:41)
import { describe, it, expect } from "vitest";
// [worker-ants] generated by AI Agent (2026-03-16 20:18:56)
import {
  initGame,
  startGame,
  togglePause,
  tick,
  moveLeft,
  moveRight,
  softDrop,
  hardDrop,
  rotate,
  getGhostRow,
} from "../gameEngine";
import { GameState, ActivePiece } from "../types";
import { getShape } from "../tetrominoes";
import { createEmptyBoard } from "../board";
import { BOARD_COLS, BOARD_ROWS, SOFT_DROP_POINTS, HARD_DROP_POINTS } from "../constants";
// /[worker-ants] generated by AI Agent (2026-03-16 20:18:56)

function runningState(): GameState {
  return { ...initGame(), isStarted: true, isPaused: false };
}

describe("initGame", () => {
  it("returns state with isStarted: false, isPaused: true, isGameOver: false", () => {
    const state = initGame();
    expect(state.isStarted).toBe(false);
    expect(state.isPaused).toBe(true);
    expect(state.isGameOver).toBe(false);
  });

  it("returns state with score: 0, level: 0, linesCleared: 0", () => {
    const state = initGame();
    expect(state.score).toBe(0);
    expect(state.level).toBe(0);
    expect(state.linesCleared).toBe(0);
  });
});

describe("tick", () => {
  it("does nothing when isGameOver is true (returns same reference)", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = tick(state);
    expect(result).toBe(state);
  });

  it("does nothing when isPaused is true (returns same reference)", () => {
    const state = { ...runningState(), isPaused: true };
    const result = tick(state);
    expect(result).toBe(state);
  });

  it("does nothing when isStarted is false (returns same reference)", () => {
    const state = { ...runningState(), isStarted: false };
    const result = tick(state);
    expect(result).toBe(state);
  });

  it("moves piece down by 1 row when game is running", () => {
    const state = runningState();
    const originalRow = state.activePiece.row;
    const result = tick(state);
    expect(result.activePiece.row).toBe(originalRow + 1);
  });
});

describe("startGame", () => {
  it("sets isStarted: true and isPaused: false from initial state", () => {
    const state = initGame();
    const result = startGame(state);
    expect(result.isStarted).toBe(true);
    expect(result.isPaused).toBe(false);
  });

  it("returns same state if already started", () => {
    const state = runningState();
    const result = startGame(state);
    expect(result).toBe(state);
  });

  it("returns same state if game is over", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = startGame(state);
    expect(result).toBe(state);
  });
});

describe("togglePause", () => {
  it("toggles isPaused when game is started", () => {
    const state = runningState();
    expect(state.isPaused).toBe(false);
    const paused = togglePause(state);
    expect(paused.isPaused).toBe(true);
    const unpaused = togglePause(paused);
    expect(unpaused.isPaused).toBe(false);
  });

  it("does nothing before game starts (isStarted: false)", () => {
    const state = initGame();
    const result = togglePause(state);
    expect(result).toBe(state);
  });

  it("does nothing when game is over", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = togglePause(state);
    expect(result).toBe(state);
  });
});

describe("moveLeft", () => {
  it("does nothing when isPaused (returns same reference)", () => {
    const state = { ...runningState(), isPaused: true };
    const result = moveLeft(state);
    expect(result).toBe(state);
  });

  it("does nothing when isGameOver (returns same reference)", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = moveLeft(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted (returns same reference)", () => {
    const state = { ...runningState(), isStarted: false };
    const result = moveLeft(state);
    expect(result).toBe(state);
  });
});

describe("moveRight", () => {
  it("does nothing when isPaused (returns same reference)", () => {
    const state = { ...runningState(), isPaused: true };
    const result = moveRight(state);
    expect(result).toBe(state);
  });

  it("does nothing when isGameOver (returns same reference)", () => {
    const state = { ...runningState(), isGameOver: true };
    const result = moveRight(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted (returns same reference)", () => {
    const state = { ...runningState(), isStarted: false };
    const result = moveRight(state);
    expect(result).toBe(state);
  });
});

describe("softDrop", () => {
  it("does nothing when isPaused", () => {
    const state = { ...runningState(), isPaused: true };
    const result = softDrop(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted", () => {
    const state = { ...runningState(), isStarted: false };
    const result = softDrop(state);
    expect(result).toBe(state);
  });
});

describe("hardDrop", () => {
  it("does nothing when isPaused", () => {
    const state = { ...runningState(), isPaused: true };
    const result = hardDrop(state);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted", () => {
    const state = { ...runningState(), isStarted: false };
    const result = hardDrop(state);
    expect(result).toBe(state);
  });
});

describe("rotate", () => {
  it("does nothing when isPaused", () => {
    const state = { ...runningState(), isPaused: true };
    const result = rotate(state, 1);
    expect(result).toBe(state);
  });

  it("does nothing when !isStarted", () => {
    const state = { ...runningState(), isStarted: false };
    const result = rotate(state, 1);
    expect(result).toBe(state);
  });
});

// [worker-ants] generated by AI Agent (2026-03-16 20:19:34)
// --- New test cases added below ---

function makeRunningStateWithPiece(
  type: ActivePiece["type"],
  row: number,
  col: number,
  rotationIndex = 0
): GameState {
  const shape = getShape(type, rotationIndex);
  return {
    ...runningState(),
    activePiece: { type, shape, row, col, rotationIndex },
  };
}

describe("moveLeft (movement)", () => {
  it("decreases column by 1 when valid", () => {
    const state = makeRunningStateWithPiece("T", 5, 5);
    const result = moveLeft(state);
    expect(result.activePiece.col).toBe(4);
  });

  it("does not move when blocked by left wall", () => {
    // T shape: [[0,1,0],[1,1,1],[0,0,0]] - leftmost filled cell at col index 0 in row 1
    // At col=0, moving left would put col index 0 at boardCol=-1
    const state = makeRunningStateWithPiece("T", 5, 0);
    const result = moveLeft(state);
    expect(result.activePiece.col).toBe(0);
  });
});

describe("moveRight (movement)", () => {
  it("increases column by 1 when valid", () => {
    const state = makeRunningStateWithPiece("T", 5, 4);
    const result = moveRight(state);
    expect(result.activePiece.col).toBe(5);
  });

  it("does not move when blocked by right wall", () => {
    // T shape is 3 wide. At col=BOARD_COLS-3, rightmost filled at boardCol=BOARD_COLS-1
    // Moving right would put it at BOARD_COLS which is invalid
    const state = makeRunningStateWithPiece("T", 5, BOARD_COLS - 3);
    const result = moveRight(state);
    expect(result.activePiece.col).toBe(BOARD_COLS - 3);
  });
});

describe("softDrop (movement)", () => {
  it("moves piece down by 1 row", () => {
    const state = makeRunningStateWithPiece("T", 5, 4);
    const result = softDrop(state);
    expect(result.activePiece.row).toBe(6);
  });

  it("adds SOFT_DROP_POINTS to score", () => {
    const state = makeRunningStateWithPiece("T", 5, 4);
    const result = softDrop(state);
    expect(result.score).toBe(state.score + SOFT_DROP_POINTS);
  });

  it("does not move when at bottom", () => {
    // T shape: rows 0 and 1 have filled cells. At row = BOARD_ROWS - 2, row index 1 is at BOARD_ROWS - 1 (last valid)
    // Moving down would put row index 1 at BOARD_ROWS which is invalid
    const state = makeRunningStateWithPiece("T", BOARD_ROWS - 2, 4);
    const result = softDrop(state);
    expect(result.activePiece.row).toBe(BOARD_ROWS - 2);
    expect(result.score).toBe(state.score); // no points added
  });
});

describe("hardDrop (movement)", () => {
  it("moves piece to bottom", () => {
    const state = makeRunningStateWithPiece("O", 0, 4);
    const result = hardDrop(state);
    // After hard drop the piece is locked and a new piece spawns
    // The O piece should have been placed at the bottom of the board
    // Check that the board has the O piece at the bottom
    expect(result.board[BOARD_ROWS - 1][4].filled).toBe(true);
    expect(result.board[BOARD_ROWS - 1][5].filled).toBe(true);
    expect(result.board[BOARD_ROWS - 2][4].filled).toBe(true);
    expect(result.board[BOARD_ROWS - 2][5].filled).toBe(true);
  });

  it("adds HARD_DROP_POINTS per row dropped", () => {
    const state = makeRunningStateWithPiece("O", 0, 4);
    const initialScore = state.score;
    const result = hardDrop(state);
    // O piece at row 0 drops to row BOARD_ROWS - 2 (since O is 2 tall)
    const expectedDropDistance = BOARD_ROWS - 2;
    const expectedDropScore = expectedDropDistance * HARD_DROP_POINTS;
    // Score includes drop points (line clear points may also be added but on empty board there shouldn't be any)
    expect(result.score).toBe(initialScore + expectedDropScore);
  });

  it("locks piece and spawns new one", () => {
    const state = makeRunningStateWithPiece("O", 0, 4);
    const result = hardDrop(state);
    // A new piece should be spawned (different from the dropped one potentially)
    // The active piece should be at or near the top
    expect(result.activePiece.row).toBe(0);
    // Board should have the locked piece
    expect(result.board[BOARD_ROWS - 1][4].filled).toBe(true);
  });
});

describe("rotate (movement)", () => {
  it("rotates piece clockwise", () => {
    const state = makeRunningStateWithPiece("T", 5, 4, 0);
    const result = rotate(state, 1);
    expect(result.activePiece.rotationIndex).toBe(1);
  });

  it("rotates piece counter-clockwise", () => {
    const state = makeRunningStateWithPiece("T", 5, 4, 0);
    const result = rotate(state, -1);
    expect(result.activePiece.rotationIndex).toBe(3);
  });
});

describe("getGhostRow", () => {
  it("returns bottom-most valid row for piece on empty board", () => {
    const state = makeRunningStateWithPiece("O", 0, 4);
    const ghostRow = getGhostRow(state);
    // O piece is 2 tall, so bottom-most row is BOARD_ROWS - 2
    expect(ghostRow).toBe(BOARD_ROWS - 2);
  });

  it("returns row above filled cells", () => {
    const state = makeRunningStateWithPiece("O", 0, 4);
    // Fill row BOARD_ROWS - 3 at cols 4 and 5 to block O piece
    state.board[BOARD_ROWS - 3][4] = { filled: true, color: "#ff0000" };
    const ghostRow = getGhostRow(state);
    // O piece at col 4: fills (row, 4), (row, 5), (row+1, 4), (row+1, 5)
    // Row+1 must be < BOARD_ROWS-3, so row = BOARD_ROWS - 4 at most... but cell is at (BOARD_ROWS-3, 4)
    // At ghostRow = BOARD_ROWS - 4: bottom of O is at BOARD_ROWS - 3, which overlaps
    // At ghostRow = BOARD_ROWS - 5: bottom at BOARD_ROWS - 4, which is fine
    expect(ghostRow).toBe(BOARD_ROWS - 5);
  });
});

describe("tick (locking)", () => {
  it("locks piece when it cannot move down", () => {
    // Place piece at bottom so tick triggers lock
    const state = makeRunningStateWithPiece("O", BOARD_ROWS - 2, 4);
    const result = tick(state);

    // Piece should be locked - board should have the O piece cells filled
    expect(result.board[BOARD_ROWS - 2][4].filled).toBe(true);
    expect(result.board[BOARD_ROWS - 1][4].filled).toBe(true);
    // A new piece should spawn
    expect(result.activePiece.row).toBe(0);
  });
});

// /[worker-ants] generated by AI Agent (2026-03-14 14:57:41)
// /[worker-ants] generated by AI Agent (2026-03-16 20:19:34)
