// [worker-ants] generated by AI Agent (2026-03-16 20:18:39)
import { describe, it, expect } from "vitest";
import { gameReducer } from "../reducer";
import { initGame } from "../gameEngine";
import { GameState, GameAction } from "../types";

function runningState(): GameState {
  return { ...initGame(), isStarted: true, isPaused: false };
}

describe("gameReducer", () => {
  it("RESTART action creates fresh running state", () => {
    const state = runningState();
    // Modify state to verify it gets reset
    state.score = 999;
    state.level = 5;
    state.linesCleared = 50;

    const result = gameReducer(state, { type: "RESTART" });

    expect(result.score).toBe(0);
    expect(result.level).toBe(0);
    expect(result.linesCleared).toBe(0);
    expect(result.isStarted).toBe(true);
    expect(result.isPaused).toBe(false);
    expect(result.isGameOver).toBe(false);
  });

  it("START action starts the game", () => {
    const state = initGame(); // not started, paused
    const result = gameReducer(state, { type: "START" });

    expect(result.isStarted).toBe(true);
    expect(result.isPaused).toBe(false);
  });

  it("TICK delegates to tick function", () => {
    const state = runningState();
    const originalRow = state.activePiece.row;
    const result = gameReducer(state, { type: "TICK" });

    expect(result.activePiece.row).toBe(originalRow + 1);
  });

  it("unknown action returns same state", () => {
    const state = runningState();
    const result = gameReducer(state, { type: "UNKNOWN" } as unknown as GameAction);

    expect(result).toBe(state);
  });

  it("MOVE_LEFT is handled", () => {
    const state = runningState();
    const originalCol = state.activePiece.col;
    const result = gameReducer(state, { type: "MOVE_LEFT" });

    expect(result.activePiece.col).toBe(originalCol - 1);
  });

  it("MOVE_RIGHT is handled", () => {
    const state = runningState();
    const originalCol = state.activePiece.col;
    const result = gameReducer(state, { type: "MOVE_RIGHT" });

    expect(result.activePiece.col).toBe(originalCol + 1);
  });

  it("SOFT_DROP is handled", () => {
    const state = runningState();
    const originalRow = state.activePiece.row;
    const result = gameReducer(state, { type: "SOFT_DROP" });

    expect(result.activePiece.row).toBe(originalRow + 1);
  });

  it("HARD_DROP is handled", () => {
    const state = runningState();
    const result = gameReducer(state, { type: "HARD_DROP" });

    // After hard drop, a new piece is spawned (piece was locked)
    expect(result.score).toBeGreaterThan(0);
  });

  it("ROTATE_CW is handled", () => {
    const state = runningState();
    const result = gameReducer(state, { type: "ROTATE_CW" });

    // Rotation should change rotationIndex (may or may not succeed depending on piece type/position)
    expect(result).toBeDefined();
  });

  it("ROTATE_CCW is handled", () => {
    const state = runningState();
    const result = gameReducer(state, { type: "ROTATE_CCW" });

    expect(result).toBeDefined();
  });

  it("TOGGLE_PAUSE is handled", () => {
    const state = runningState();
    expect(state.isPaused).toBe(false);

    const result = gameReducer(state, { type: "TOGGLE_PAUSE" });
    expect(result.isPaused).toBe(true);

    const result2 = gameReducer(result, { type: "TOGGLE_PAUSE" });
    expect(result2.isPaused).toBe(false);
  });
});

// /[worker-ants] generated by AI Agent (2026-03-16 20:18:39)
