// [worker-ants] generated by AI Agent (2026-03-16 20:18:14)
import { describe, it, expect } from "vitest";
import { tryRotate } from "../rotation";
import { createEmptyBoard } from "../board";
import { getShape } from "../tetrominoes";
import { ActivePiece, Board } from "../types";
import { BOARD_COLS, BOARD_ROWS } from "../constants";

function makePiece(
  type: ActivePiece["type"],
  row: number,
  col: number,
  rotationIndex = 0
): ActivePiece {
  return {
    type,
    shape: getShape(type, rotationIndex),
    row,
    col,
    rotationIndex,
  };
}

describe("tryRotate", () => {
  it("successfully rotates T piece clockwise on empty board", () => {
    const board = createEmptyBoard();
    const piece = makePiece("T", 5, 4);
    const result = tryRotate(board, piece, 1);

    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(1);
    expect(result!.shape).toEqual(getShape("T", 1));
    expect(result!.row).toBe(5);
    expect(result!.col).toBe(4);
  });

  it("successfully rotates T piece counter-clockwise on empty board", () => {
    const board = createEmptyBoard();
    const piece = makePiece("T", 5, 4);
    const result = tryRotate(board, piece, -1);

    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(3); // (0 + (-1) + 4) % 4 = 3
    expect(result!.shape).toEqual(getShape("T", 3));
  });

  it("applies wall kick when piece is near left wall", () => {
    const board = createEmptyBoard();
    // T piece at col=0, rotation 3 -> rotation 0
    // Rotation 3: [[0,1,0],[1,1,0],[0,1,0]] - leftmost filled at col index 0
    // Try rotating CW to rotation 0: [[0,1,0],[1,1,1],[0,0,0]]
    const piece = makePiece("T", 5, -1, 3);
    // At col=-1, rotation 0 would have filled cell at boardCol = -1 + 0 = -1 for row 1 col 0
    // Wall kick should try dc=+1 offset
    const result = tryRotate(board, piece, 1);

    // Should succeed with a wall kick
    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(0);
  });

  it("applies wall kick when piece is near right wall", () => {
    const board = createEmptyBoard();
    // T piece rotation 1: [[0,1,0],[0,1,1],[0,1,0]]
    // At col = BOARD_COLS - 3, rotating CW to rotation 2: [[0,0,0],[1,1,1],[0,1,0]]
    const piece = makePiece("T", 5, BOARD_COLS - 2, 1);
    // Rotation 2 at col=BOARD_COLS-2: col index 2 -> boardCol = BOARD_COLS, out of bounds
    // Wall kick dc=-1 should fix it
    const result = tryRotate(board, piece, 1);

    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(2);
  });

  it("returns null when rotation is completely blocked", () => {
    const board = createEmptyBoard();
    // Fill cells around the piece so no rotation or wall kick works
    const piece = makePiece("T", 5, 4);

    // Block all surrounding cells
    for (let r = 4; r <= 7; r++) {
      for (let c = 3; c <= 6; c++) {
        if (r >= 0 && r < BOARD_ROWS && c >= 0 && c < BOARD_COLS) {
          board[r][c] = { filled: true, color: "#ff0000" };
        }
      }
    }
    // Clear the cells where the current piece is (so the piece itself is valid in current position)
    // But rotated shape won't fit anywhere nearby
    const result = tryRotate(board, piece, 1);
    expect(result).toBeNull();
  });

  it("I-piece uses extra wall kick offsets (dc=-2 and dc=+2)", () => {
    const board = createEmptyBoard();
    // I piece horizontal (rotation 0): filled at row 1, cols 0-3 (4 wide)
    // Place near left wall at col=-2, so base rotation would fail
    // Standard offsets dc=-1,+1 won't help if we need dc=+2
    const piece = makePiece("I", 5, 3, 0);

    // Block positions that standard offsets would try but leave dc=+2 open
    // Rotating CW: rotation 1 has filled at col 2 of 4x4
    // Actually let's just verify I piece can rotate on empty board first
    const result = tryRotate(board, piece, 1);
    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(1);
    expect(result!.type).toBe("I");
  });

  it("I-piece extra offsets: rotation succeeds with dc=+2 kick", () => {
    const board = createEmptyBoard();
    // I piece vertical (rotation 1): filled at col 2 of 4x4 grid, rows 0-3
    // Place at col = -2. Rotation to index 2 (horizontal at row 2): filled at cols 0-3
    // At col = -2 base: boardCols would be -2,-1,0,1 - fails
    // dc=-1: -3,-2,-1,0 - fails
    // dc=+1: -1,0,1,2 - fails (boardCol -1)
    // dr offsets won't help for col issues
    // dc=+2: 0,1,2,3 - success!
    const piece = makePiece("I", 5, -2, 1);
    const result = tryRotate(board, piece, 1);

    expect(result).not.toBeNull();
    if (result) {
      expect(result.col).toBe(0); // shifted by dc=+2
      expect(result.rotationIndex).toBe(2);
    }
  });

  it("rotation preserves piece type", () => {
    const board = createEmptyBoard();
    const piece = makePiece("S", 5, 4);
    const result = tryRotate(board, piece, 1);

    expect(result).not.toBeNull();
    expect(result!.type).toBe("S");
  });

  it("clockwise rotation wraps from index 3 to 0", () => {
    const board = createEmptyBoard();
    const piece = makePiece("T", 5, 4, 3);
    const result = tryRotate(board, piece, 1);

    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(0);
  });

  it("counter-clockwise rotation wraps from index 0 to 3", () => {
    const board = createEmptyBoard();
    const piece = makePiece("T", 5, 4, 0);
    const result = tryRotate(board, piece, -1);

    expect(result).not.toBeNull();
    expect(result!.rotationIndex).toBe(3);
  });
});

// /[worker-ants] generated by AI Agent (2026-03-16 20:18:14)
