// [worker-ants] generated by AI Agent (2026-03-16 20:18:27)
import { describe, it, expect } from "vitest";
import { calculateScore, getLevel, getDropInterval } from "../scoring";
import {
  BASE_DROP_INTERVAL,
  DROP_INTERVAL_DECREASE,
  MIN_DROP_INTERVAL,
  LINES_PER_LEVEL,
} from "../constants";

describe("calculateScore", () => {
  it("returns 0 when 0 lines cleared", () => {
    expect(calculateScore(0, 0)).toBe(0);
    expect(calculateScore(0, 5)).toBe(0);
  });

  it("1 line = 100 * (level + 1)", () => {
    expect(calculateScore(1, 0)).toBe(100);
    expect(calculateScore(1, 1)).toBe(200);
    expect(calculateScore(1, 4)).toBe(500);
  });

  it("2 lines = 300 * (level + 1)", () => {
    expect(calculateScore(2, 0)).toBe(300);
    expect(calculateScore(2, 1)).toBe(600);
    expect(calculateScore(2, 3)).toBe(1200);
  });

  it("3 lines = 500 * (level + 1)", () => {
    expect(calculateScore(3, 0)).toBe(500);
    expect(calculateScore(3, 1)).toBe(1000);
    expect(calculateScore(3, 2)).toBe(1500);
  });

  it("4 lines (tetris) = 800 * (level + 1)", () => {
    expect(calculateScore(4, 0)).toBe(800);
    expect(calculateScore(4, 1)).toBe(1600);
    expect(calculateScore(4, 5)).toBe(4800);
  });

  it("higher levels multiply score correctly", () => {
    expect(calculateScore(1, 9)).toBe(1000);
    expect(calculateScore(4, 9)).toBe(8000);
  });

  it("5+ lines returns 0 (not in scoring table)", () => {
    expect(calculateScore(5, 0)).toBe(0);
    expect(calculateScore(6, 3)).toBe(0);
    expect(calculateScore(10, 0)).toBe(0);
  });
});

describe("getLevel", () => {
  it("0 lines = level 0", () => {
    expect(getLevel(0)).toBe(0);
  });

  it("9 lines = level 0", () => {
    expect(getLevel(9)).toBe(0);
  });

  it("10 lines = level 1", () => {
    expect(getLevel(10)).toBe(1);
  });

  it("25 lines = level 2", () => {
    expect(getLevel(25)).toBe(2);
  });

  it("respects LINES_PER_LEVEL constant", () => {
    expect(getLevel(LINES_PER_LEVEL)).toBe(1);
    expect(getLevel(LINES_PER_LEVEL * 3)).toBe(3);
    expect(getLevel(LINES_PER_LEVEL - 1)).toBe(0);
  });
});

describe("getDropInterval", () => {
  it("level 0 returns BASE_DROP_INTERVAL", () => {
    expect(getDropInterval(0)).toBe(BASE_DROP_INTERVAL);
  });

  it("higher levels decrease interval", () => {
    const level1 = getDropInterval(1);
    const level2 = getDropInterval(2);
    expect(level1).toBe(BASE_DROP_INTERVAL - DROP_INTERVAL_DECREASE);
    expect(level2).toBe(BASE_DROP_INTERVAL - 2 * DROP_INTERVAL_DECREASE);
    expect(level2).toBeLessThan(level1);
  });

  it("never goes below MIN_DROP_INTERVAL", () => {
    // At very high levels
    const veryHighLevel = 100;
    expect(getDropInterval(veryHighLevel)).toBe(MIN_DROP_INTERVAL);
  });

  it("returns MIN_DROP_INTERVAL at exact threshold level", () => {
    // Find the level where interval would go below MIN
    const thresholdLevel = Math.ceil(
      (BASE_DROP_INTERVAL - MIN_DROP_INTERVAL) / DROP_INTERVAL_DECREASE
    );
    expect(getDropInterval(thresholdLevel)).toBe(MIN_DROP_INTERVAL);
    expect(getDropInterval(thresholdLevel + 1)).toBe(MIN_DROP_INTERVAL);
  });
});

// /[worker-ants] generated by AI Agent (2026-03-16 20:18:27)
